### ISSUE TITLE
DOC: How to create testing environments

### ISSUE THREAD

**Issue by jakirkham** [dask/dask-image#103]
Add a note to CONTRIBUTING.rst under the headings 'Fix bugs' and 'Implement features' to say how to create the development conda environment (they're hiding in the hidden folders for travis, appveyor and circleCI). As an example, PR ( https://github.com/dask/dask-image/pull/90 ) shows the text added for testing the docs.

**Comment by GenevieveBuckley** [comment]
* Appveyor has our Windows envrionments `.appveyor_support/environments/...`
* Travis has our MacOS environments`.travis_support/environments/...`
* CircleCI has our Linux environnments`.circleci/environments/...`

**Comment by GenevieveBuckley** [comment]
The way we create conda environments from an environment yml file is like this: `conda env create -f environment.yml`

https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file

**Comment by GenevieveBuckley** [comment]
So in our case, we might do something like this...

I'll assume we have cloned dask-image, and changed directory into the top level of the repository.
Then, to make the test environment for Windows with Python 3.8, we would do this:
```
conda env create -f .appveyor_support\environments\tst_py38.yml
```
This command will create a new conda environment for use called `dask_image_py38_env` (you can see what the name of the new environment is by looking at the contents of the .yml file).

Then, to run the tests...
1. Activate your test environment, eg: `conda activate dask_image_py38_env`
2. Install the development version of dask-image: `pip install -e .`
3. Run pytest: `pytest`
