### ISSUE TITLE
Feature request: convenience function to calculate label area

### ISSUE THREAD

**Issue by GenevieveBuckley** [dask/dask-image#106]
### Description
Feature request: a convenience function for calculating the area of label regions in an image.

I was thinking about creating a function `dask_image.ndmeasure.area()` to calculate the area of label regions given a labelled image (Juan suggests I base it around using  `dask.array.bincount()`). Measuring the area of segmented objects is a common to many types of quantitative image analysis, so I think it makes sense to have a convenience function for it.

This issue is for discussion, including discussion on the consistency with the rest of the dask-image API.

**Comment by GenevieveBuckley** [comment]
Regarding API consistency:

I think it makes sense to restrict the function to calculate area, so it only accepts input of integer type label images:

```
from dask_image import ndmeasure
result = ndmeasure.area(labels, index=None, minlength=None)  # minlength is a required argument for dask.array.bincount()
```

Whereas most dask-image ndmeasure functions use a call like:

```
result = ndmeasure.function_name(input, labels=None, index=None)
```

If this difference is clearly spelled out in the documentation, is this a non-issue?

**Comment by jakirkham** [comment]
Thanks for raising @GenevieveBuckley.

FWIW I had an `area` implementation on a precursor library ( https://github.com/dask-image/dask-ndmeasure/pull/79 ), which I had intended to port over. Maybe that works for your use case. WDYT?

**Comment by GenevieveBuckley** [comment]
Yes, I think it would :)

It's worth checking that the API stays consistent if we use it as is, or if there's any slight tweaking necessary. I don't have a ton of time right now, but could come back to this in a few weeks, perhaps.
