### ISSUE TITLE
dask_image.ndfilters.gaussian_filter

### ISSUE THREAD

**Issue by DanielOrtega94** [dask/dask-image#114]
* dask-image version: 0.20
* Python version: 3.6
* Operating System: ubuntu 18.10
* numpy version: 1.16.2

running on conda enviroment

### Description
i get an error when i try to execute dask_image.ndfilters.gaussian_filter

### What I Did
this is the code:

```
for i, pt in enumerate(pts):
        pt2d = np.zeros(gt.shape, dtype=np.float32)
        pt2d[pt[1],pt[0]] = 1.
        if gt_count > 1:
            sigma = (distances[i][1]+distances[i][2]+distances[i][3])*0.1
        else:
            sigma = np.average(np.array(gt.shape))/2./2. #case: 1 point
        density += dask_image.ndfilters.gaussian_filter(pt2d, sigma)
```

and this is the error:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-22-5187b73d47ca> in <module>
----> 1 gaussian_filter_density_fast(k)

```
<ipython-input-18-b49a9fa75c29> in gaussian_filter_density_fast(gt)
     23         else:
     24             sigma = np.average(np.array(gt.shape))/2./2. #case: 1 point
---> 25         density += dask_image.ndfilters.gaussian_filter(pt2d, sigma)
     26     print ('done.')
     27     return density

~/anaconda3/lib/python3.6/site-packages/dask_image/ndfilters/_gaussian.py in gaussian_filter(input, sigma, order, mode, cval, truncate)
     58     depth, boundary = _utils._get_depth_boundary(input.ndim, depth, "none")
     59 
---> 60     result = input.map_overlap(
     61         scipy.ndimage.filters.gaussian_filter,
     62         depth=depth,

AttributeError: 'numpy.ndarray' object has no attribute 'map_overlap'
```

**Comment by DanielOrtega94** [comment]
I use a dask array to Solve muy problem.
Sorry forma post a issue

**Comment by jakirkham** [comment]
Hi @DanielOrtega94, thanks for dropping by. So I think I missed something. What were you using instead of a Dask Array before?

**Comment by jni** [comment]
@jakirkham based on the error, it's a NumPy array.
