### ISSUE TITLE
Rename `ndmeasure`'s `sum` function

### ISSUE THREAD

**Issue by jakirkham** [dask/dask-image#123]
The [`sum` function in `ndmeasure` here]( https://dask-image.readthedocs.io/en/latest/dask_image.ndmeasure.html#dask_image.ndmeasure.sum ) overlaps with [the `sum` builtin]( https://docs.python.org/3/library/functions.html#sum ). Basically this is a consequence of following [the SciPy API]( https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.sum.html#scipy.ndimage.sum ). That said, it would be nice to improve things here. Though it would be good to see if SciPy is amenable to such a change first and if so follow their lead. ( https://github.com/scipy/scipy/issues/10593 )

**Comment by jakirkham** [comment]
SciPy recently renamed this ( https://github.com/scipy/scipy/pull/12242 ). We should consider doing the same.

**Comment by abhisht51** [comment]
What would you propose I rename the function to? @jakirkham ```ndmeasure_sum? ```

**Comment by jakirkham** [comment]
Would propose aligning with SciPy. They chose `sum_labels`. So would suggest we do the same.

**Comment by abhisht51** [comment]
Alright! 
I do not think any other change except the change in function name is required. Correct me if I am wrong.

**Comment by jakirkham** [comment]
I guess there’s a question of whether we want to do a depreciation cycle

**Comment by abhisht51** [comment]
I guess one should? How would you propose I move forward then? Add an exactly same function with ```sum_labels``` name and add a ```@deprecated``` decorator for the ```sum``` function? Is that available for this project?

**Comment by jakirkham** [comment]
Would rename the function and a new `sum` function, which issues a `DeprecationWarning` before calling `sum_labels`.

**Comment by GenevieveBuckley** [comment]
So scipy versions < 1.5.0 have this function named `sum`, while scipy versions >= 1.5.0 call this function `sum_labels`.

I will fix the tests in the PR by @tkoyama010 to check which version of scipy is installed and choose the right name for that version.

**Comment by GenevieveBuckley** [comment]
Closed via https://github.com/dask/dask-image/pull/172
