### ISSUE TITLE
Support pathlib Path input in dask_image.imread.imread()

### ISSUE THREAD

**Issue by GenevieveBuckley** [dask/dask-image#139]
It would be good if we supported [pathlib](https://docs.python.org/3/library/pathlib.html) Path inputs into the dask-image `imread()` function. I don't think it should be too complicated to add, so this could be a good first issue for contributors to `dask-image`.

**Comment by martindurant** [comment]
If dask-image uses `fsspec.open_files`, then you could achieve this easily by calling [`stringify_path`](https://github.com/intake/filesystem_spec/blob/master/fsspec/utils.py#L281) in the first line of `open_files`

**Comment by martindurant** [comment]
(feel free to use `stringify_path` even if you don't otherwise depend on `fsspec`, of course :) )

**Comment by tlambert03** [comment]
there's also [`os.fspath`](https://docs.python.org/3/library/os.html#os.fspath) ... but that's probably not worth dropping support for py3.5? :)

**Comment by martindurant** [comment]
`os.fspath` is almost identical to `isinstance(urlpath, Path)`; then again, pathlib only appeared in py34.

Does dask-image support remote reading at all?

**Comment by GenevieveBuckley** [comment]
Hi @martindurant, dask-image does not use `fsspec`, we use [pims](https://github.com/soft-matter/pims). I do like `stringify_path` though, thanks for mentioning it!

Currently there isn't support for remote reading of files in dask-image. Pims *does* have support for remotely reading data via `pims.ImageSequence()`, but the more generalized `pims.open()` (which dask-image uses) does not share the same support. You can read a discussion about this at https://github.com/soft-matter/pims/issues/310 and the work John did towards a solution at https://github.com/soft-matter/pims/pull/316.

**Comment by martindurant** [comment]
cc @danielballan , who worked on PIMS and we talked about this a little.
(@jakirkham , you are also maybe interested in this)

**Comment by jakirkham** [comment]
Supporting pathlib seems sensible.

FWIW Dan started working on [a prototype for PIMS 2]( https://github.com/danielballan/pims2-prototype ). Maybe these would be good suggestions for that prototype? Dask-image really relies on other libraries to do the heavy lifting (and doesn't try to get too involved itself).

**Comment by GenevieveBuckley** [comment]
> FWIW Dan started working on [a prototype for PIMS 2](https://github.com/danielballan/pims2-prototype). Maybe these would be good suggestions for that prototype?

Ok, [done](https://github.com/danielballan/pims2-prototype/issues/3)

> Dask-image really relies on other libraries to do the heavy lifting (and doesn't try to get too involved itself).

When I say "support" from dask-image, I think that should just mean try coercing any Paths to strings for convenience, at least as long as we're calling out to a library that only accepts strings.

**Comment by jakirkham** [comment]
Yeah that’s what I figured you meant by support as well. That’s what I was trying to respond to in the first line. So yeah let’s support pathlib.

Was trying to say more involved solutions are probably something we want to handle in a proper image reading library.

**Comment by GenevieveBuckley** [comment]
One thing to double check when working on this is whether we currently support passing lists of filenames, as well as just a single string. (I can't remember if this is true or not). If it is true, the solution to this issue will also need to work in that situation as well.

**Comment by GenevieveBuckley** [comment]
Closed via https://github.com/dask/dask-image/pull/174
