### ISSUE TITLE
Calling Scikit image or ndimage to dask array just creates a never ending function and computes without actually calling compute.

### ISSUE THREAD

**Issue by Sh4zKh4n** [dask/dask-image#153]
Hi,

When working with a large data dask shows some promise but I cant repeat similar actions that have been shown elsewhere, I havent been able to get dask to work with bigger than ram data with other libraries.  I am unable to get any libraries like Scikit image to not call or compute immediately. It is if calling them persists to memory. I just get stuck in a loop that is either memory issue or I get stuck with a loop with my hard drive reading and writing but not to a folder. These should all be futures or delayed functions until I call them? shouldnt they? This is a problem even if I use map_blocks or Map overlay, it just tries to stick all the array into memory instead of flushing to a zarr file. Everytime I call a library or a function unless it's ufunc manipulations, this seems to computer and try to pull into memory. Which with 16GB of ram isn't going to happen.

I can run pixel manipulations, 40GB or 300GB files, quite easily and having a super fast contrast stretch, dask histogram works when I chunk around 50MB,  I manually built with pixel wise function with Ufunc and its great. It just means all the examples that Ive read around just never work. I have even cleaned my computer once and it doesnt work. The below code has now been running for 20 mins without any changes just my hard drive writing something and nothing else. Is there some global state that can turn of libraries from persisting to memory unless compute is called or saved to file? Ill add my enviroment details soon.

 Example is below:
-----
import numpy as np
import scipy
import scipy.ndimage
import matplotlib 
import matplotlib.pyplot as plt
%matplotlib inline
import dask
import dask.array as da
from dask.diagnostics import ProgressBar
import os
import zarr
pbar = ProgressBar()
pbar.register()

plt.rcParams["figure.figsize"] = (10,10)
import gc
gc.collect()

da_Colz = da.from_zarr('E:\Col_Zarr_CS\mask\med.zarr')
da_Colz

image=da_Colz

from skimage.transform import rescale

image_rescaled = rescale(image, 0.25, preserve_range=True ,anti_aliasing=True, )

--------------------

![image](https://user-images.githubusercontent.com/49095152/90957977-fe382900-e488-11ea-8b5a-ab92630ce8a0.png)

**Environment**:

- Dask version: see enviroment below
- Python version: 3.77
- Operating System: windows 10 64bit
- Install method Conda
enviroment:

# Name                    Version                   Build  Channel
_pytorch_select           0.1                       cpu_0
alabaster                 0.7.12                   py37_0
asciitree                 0.3.3                      py_2
attrs                     19.3.0                     py_0
babel                     2.8.0                      py_0
backcall                  0.2.0                      py_0
blas                      1.0                         mkl
bleach                    3.1.5                      py_0
blosc                     1.19.0               h7bd577a_0
bokeh                     2.0.2                    py37_0
brotli                    1.0.7                h33f27b4_0
brotlipy                  0.7.0           py37he774522_1000
bzip2                     1.0.8                he774522_0
ca-certificates           2020.6.24                     0
cachey                    0.2.1              pyh9f0ad1d_0    conda-forge
certifi                   2020.6.20                py37_0
cffi                      1.14.0           py37h7a1dbc1_0
cftime                    1.2.1            py37h2a96729_0
chardet                   3.0.4                 py37_1003
charls                    2.1.0                h33f27b4_2
click                     7.1.2                      py_0
cloudpickle               1.5.0                      py_0
colorama                  0.4.3                      py_0
colorcet                  2.0.2                      py_0
conda                     4.8.4                    py37_0
conda-package-handling    1.6.1            py37h62dcd97_0
cryptography              2.9.2            py37h7a1dbc1_0
cudatoolkit               10.0.130                      0
cudnn                     7.6.5                cuda10.0_0
cupy                      6.0.0            py37h230ac6f_0
curl                      7.71.1               h2a8f88b_1
cycler                    0.10.0                   py37_0
cython                    0.29.21          py37h1834ac0_0    conda-forge
cytoolz                   0.10.1           py37he774522_0
dask                      2.17.2                     py_0
dask-core                 2.17.2                     py_0
dask-image                0.3.0              pyh9f0ad1d_0    conda-forge
datashader                0.11.1                     py_0
datashape                 0.5.4                    py37_1
decorator                 4.4.2                      py_0
defusedxml                0.6.0                      py_0
distributed               2.23.0                   py37_0
docutils                  0.16                     py37_1
entrypoints               0.3                      py37_0
fasteners                 0.15                       py_0
fastparquet               0.3.2            py37h2a96729_0
fastrlock                 0.4              py37h6538335_0
freetype                  2.10.2               hd328e21_0
freetype-py               2.2.0              pyh9f0ad1d_0    conda-forge
fsspec                    0.7.4                      py_0
giflib                    5.2.1                h2fa13f4_2    conda-forge
hdf4                      4.2.13               h712560f_2
hdf5                      1.10.4               h7ebc959_0
heapdict                  1.0.1                      py_0
holoviews                 1.13.3                     py_0
holoviz                   0.11.6                     py_0    pyviz
hvplot                    0.6.0                      py_1
icc_rt                    2019.0.0             h0cc432a_1
icu                       64.2                 he025d50_1    conda-forge
idna                      2.10                       py_0
imagecodecs               2020.5.30        py37h92c78e3_2    conda-forge
imageio                   2.9.0                      py_0
imagesize                 1.2.0                      py_0
importlib-metadata        1.7.0                    py37_0
importlib_metadata        1.7.0                         0
intel-openmp              2019.4                      245
ipydatawidgets            4.0.1              pyh9f0ad1d_1    conda-forge
ipykernel                 5.3.3            py37h5ca1d4c_0
ipympl                    0.3.3                      py_0
ipython                   7.17.0           py37h39e3cac_0
ipython_genutils          0.2.0                    py37_0
ipywidgets                7.5.1                      py_0
itk                       5.1.0            py37hc8dfbb8_2    conda-forge
itk-core                  5.1.0.post3              pypi_0    pypi
itk-filtering             5.1.0.post3              pypi_0    pypi
itk-numerics              5.1.0.post3              pypi_0    pypi
itk-registration          5.1.0.post3              pypi_0    pypi
itkwidgets                0.31.4           py37hc8dfbb8_0    conda-forge
jedi                      0.17.2                   py37_0
jinja2                    2.11.2                     py_0
joblib                    0.16.0                     py_0
jpeg                      9d                   he774522_0    conda-forge
json5                     0.9.5                      py_0
jsonschema                3.2.0                    py37_1
jupyter_client            6.1.6                      py_0
jupyter_core              4.6.3                    py37_0
jupyterlab                2.2.0                      py_0    conda-forge
jupyterlab_server         1.2.0                      py_0
jxrlib                    1.1                  he774522_2
kiwisolver                1.2.0            py37h74a9793_0
krb5                      1.18.2               hc04afaa_0
lcms2                     2.11                 hc51a39a_0
lerc                      2.2                  ha925a31_0    conda-forge
libaec                    1.0.4                h33f27b4_1
libblas                   3.8.0                    14_mkl    conda-forge
libcblas                  3.8.0                    14_mkl    conda-forge
libclang                  9.0.1           default_hf44288c_0
libcurl                   7.71.1               h2a8f88b_1
libiconv                  1.15                 h1df5818_7
libmklml                  2019.0.5                      0
libnetcdf                 4.7.3                h1302dcc_0
libpng                    1.6.37               h2a8f88b_0
libsodium                 1.0.18               h62dcd97_0
libssh2                   1.9.0                h7a1dbc1_1
libtiff                   4.1.0                h56a325e_1
libwebp-base              1.1.0                he774522_3
libxml2                   2.9.10               h464c3ec_1
libxslt                   1.1.34               he774522_0
libzopfli                 1.0.3                ha925a31_0
llvmlite                  0.31.0           py37ha925a31_0
locket                    0.2.0                    py37_1
lz4-c                     1.9.2                h62dcd97_1
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markdown                  3.2.2                    py37_0
markupsafe                1.1.1            py37hfa6e2cd_1
matplotlib                3.1.3                    py37_0
matplotlib-base           3.1.3            py37h64f37c6_0
menuinst                  1.4.16           py37he774522_1
mistune                   0.8.4           py37hfa6e2cd_1001
mkl                       2019.4                      245
mkl-service               2.3.0            py37hb782905_0
mkl_fft                   1.1.0            py37h45dec08_0
mkl_random                1.1.0            py37h675688f_0
monotonic                 1.5                        py_0
msgpack-python            1.0.0            py37h74a9793_1
msys2-conda-epoch         20160418                      1
multipledispatch          0.6.0                    py37_0
napari                    0.3.6                      py_0    conda-forge
napari-plugin-engine      0.1.6                      py_0    conda-forge
napari-svg                0.1.3                      py_0    conda-forge
nbconvert                 5.6.1                    py37_1
nbformat                  5.0.7                      py_0
netcdf4                   1.5.3            py37h012c1a0_0
networkx                  2.4                        py_1
ninja                     1.10.0           py37h7ef1ec2_0
notebook                  6.0.3            py37hc8dfbb8_1    conda-forge
numba                     0.48.0           py37h47e9c7a_0
numcodecs                 0.6.4            py37ha925a31_0
numpy                     1.18.1           py37h93ca92e_0
numpy-base                1.18.1           py37hc3f5095_1
numpydoc                  1.1.0                      py_0
olefile                   0.46                     py37_0
openjpeg                  2.3.1                h57dd2e7_3    conda-forge
openssl                   1.1.1g               he774522_1
packaging                 20.4                       py_0
pandas                    1.0.3            py37h47e9c7a_0
pandoc                    2.10.1                        0
pandocfilters             1.4.2                    py37_1
panel                     0.9.5                      py_0    pyviz
param                     1.9.3                      py_0
parso                     0.7.0              pyh9f0ad1d_0    conda-forge
partd                     1.1.0                      py_0
pickleshare               0.7.5                 py37_1001
pillow                    7.2.0            py37hcc1f983_0
pims                      0.5                        py_1
pip                       20.1.1                     py_1    conda-forge
pluggy                    0.13.1                   py37_0
prometheus_client         0.8.0                      py_0
prompt-toolkit            3.0.5                      py_0
psutil                    5.7.0            py37he774522_0
pycosat                   0.6.3            py37he774522_0
pycparser                 2.20                       py_2
pyct                      0.4.6                    py37_0
pygments                  2.6.1                      py_0
pyopengl                  3.1.1a1                  py37_0
pyopenssl                 19.1.0                     py_1
pyparsing                 2.4.7                      py_0
pyqt                      5.12.3           py37h1834ac0_3    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtchart                 5.12                     pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyrsistent                0.16.0           py37he774522_0
pyside2                   5.13.2           py37hfa7ce6d_2    conda-forge
pysocks                   1.7.1                    py37_1
python                    3.7.7                h81c818b_4
python-dateutil           2.8.1                      py_0
python-lmdb               0.96             py37h6538335_0    conda-forge
python-snappy             0.5.4            py37ha925a31_0
python_abi                3.7                     1_cp37m    conda-forge
pytorch                   1.2.0           py3.7_cuda100_cudnn7_1    pytorch
pytz                      2020.1                     py_0
pyviz_comms               0.7.6                      py_0
pywavelets                1.1.1            py37he774522_0
pywin32                   227              py37he774522_1
pywinpty                  0.5.7                    py37_0
pyyaml                    5.3.1            py37he774522_1
pyzmq                     19.0.1           py37ha925a31_1
qt                        5.12.5               h7ef1ec2_0    conda-forge
qtconsole                 4.7.5                      py_0
qtpy                      1.9.0                      py_0
requests                  2.24.0                     py_0
rise                      5.6.1                    py37_1
ruamel_yaml               0.15.87          py37he774522_1
scikit-image              0.17.2           py37h3bbf574_1    conda-forge
scikit-learn              0.23.1           py37h25d0782_0
scipy                     1.5.0            py37h9439919_0
send2trash                1.5.0                    py37_0
setuptools                49.6.0                   py37_0
six                       1.15.0                     py_0
slicerator                1.0.0                      py_0
snappy                    1.1.8                h33f27b4_0
snowballstemmer           2.0.0                      py_0
sortedcontainers          2.2.2                      py_0
sphinx                    3.2.1                      py_0
sphinxcontrib-applehelp   1.0.2                      py_0
sphinxcontrib-devhelp     1.0.2                      py_0
sphinxcontrib-htmlhelp    1.0.3                      py_0
sphinxcontrib-jsmath      1.0.1                      py_0
sphinxcontrib-qthelp      1.0.3                      py_0
sphinxcontrib-serializinghtml 1.1.4                      py_0
sqlite                    3.32.3               h2a8f88b_0
tbb                       2020.0               h74a9793_0
tblib                     1.6.0                      py_0
terminado                 0.8.3                    py37_0
testpath                  0.4.4                      py_0
threadpoolctl             2.1.0              pyh5ca1d4c_0
thrift                    0.13.0           py37ha925a31_0
tifffile                  2020.7.22                  py_0    conda-forge
tk                        8.6.10               he774522_0
toolz                     0.10.0                     py_0
torchvision               0.4.0                py37_cu100    pytorch
tornado                   6.0.4            py37he774522_1
tqdm                      4.48.2                     py_0
traitlets                 4.3.3                    py37_0
traittypes                0.2.1                      py_1    conda-forge
typing_extensions         3.7.4.2                    py_0
urllib3                   1.25.10                    py_0
vc                        14.1                 h0510ff6_4
vispy                     0.6.4            py37hbc2f12b_1    conda-forge
vs2015_runtime            14.16.27012          hf0eaf9b_3
wcwidth                   0.2.5                      py_0
webencodings              0.5.1                    py37_1
wheel                     0.34.2                   py37_0
widgetsnbextension        3.5.1                    py37_0
win_inet_pton             1.1.0                    py37_0
wincertstore              0.2                      py37_0
winpty                    0.4.3                         4
wrapt                     1.12.1           py37he774522_1
xarray                    0.15.1                     py_0
xz                        5.2.5                h62dcd97_0
yaml                      0.2.5                he774522_0
zarr                      2.4.0                      py_0    conda-forge
zeromq                    4.3.2                ha925a31_2
zfp                       0.5.5                ha925a31_1    conda-forge
zict                      2.0.0                      py_0
zipp                      3.1.0                      py_0
zlib                      1.2.11               h62dcd97_4
zstandard                 0.13.0           py37ha925a31_0
zstd                      1.4.5                h04227a9_0

**Comment by jni** [comment]
Copying over my response from the image.sc forum here, since I really don't understand why `dask_image.ndfilters.median_filter` runs fine while `scipy.ndimage.median_filter`, which it wraps, cannot process even a single chunk. Response with code snippets below. I am just a dask user, not an expert, so corrections from maintainers are very welcome, as well as speculation about what could be different.

----------------------

@Sh4zKh4n I recommend that you provide a *complete* failing example as code (not screenshots) that people can run on their own machine. StackOverflow has a [good article](https://stackoverflow.com/help/minimal-reproducible-example) on this.

This makes it much easier for people to debug your use case rather than try to think about it just from reading it, which is hard, or have to abstract away the problem.

In your case, I agree with Matt Rocklin that it seems the ndimage median filter is the failing function. Unfortunately, ndimage just does not do great for large kernel sizes. For example:

```
import numpy as np
from scipy import ndimage as ndi


def median3d(image):
    return ndi.median_filter(image, size=25)


res = median3d(
    np.random.randint(0, 256, size=(285, 245, 310)).astype(np.uint8)
)
```

ie running your code for *just* one chunk is taking forever on my machine (3min and counting), using up "only" 2GB of RAM. There is an [open issue](https://github.com/scipy/scipy/issues/4878) in SciPy about this excessive RAM usage, but it is really quite a difficult one to fix, which is why it remains open 5 years later.

Now, the thing I *totally* don't understand is why `dask_image.ndfilters.median_filter` is working at all for you, since literally [all it is doing](https://github.com/dask/dask-image/blob/cf3bde869be823acc5d2534c2c1c7d2ea4cd8846/dask_image/ndfilters/_order.py#L9-L42) is wrapping `ndimage.median_filter` in a [`map_overlap`](https://docs.dask.org/en/latest/array-overlap.html#dask.array.map_overlap) call. You can see the [source code](https://github.com/dask/dask/blob/d96fed990279fcd272cc5ada005d07c85b104ce5/dask/array/overlap.py#L541) and find that it boils down to [a `map_blocks` call](https://github.com/dask/dask/blob/d96fed990279fcd272cc5ada005d07c85b104ce5/dask/array/overlap.py#L718) just like yours. I can *also* reproduce that behaviour as follows:

```python
import numpy as np
from dask_image.ndfilters import median_filter
from dask.diagnostics import ProgressBar

pbar = ProgressBar()
pbar.register()

arr = da.random.randint(
    0, 256, size=(10260, 1225, 1550),
    dtype=np.uint8,
    chunks=(285, 245, 310)
)

smoothed = median_filter(arr, size=25)
smoothed.to_zarr('smoothed.zarr')
```

```
[#                      ] | 3% Completed |  3min 36.8s
```

But, it does eventually start using too much RAM and spilling to disk, and brings my computer to a standstill...

On that I really must say I am stumped.

Things I would try next in your situation:

- try using the [dask.distributed scheduler](https://distributed.dask.org/en/latest/) and some local workers. By default, dask.array uses the threaded scheduler, which as I understand it will request as much RAM as the OS will give, and the OS will give more than it has and spill to disk, which is inefficient. Distributed gives you fine control over the resources you allocate to each worker. We saw that a single chunk takes up about 2GB of RAM to process, so you should be good with e.g. 3 workers with 5GB each (it's good to have a bit of overhead space!).
- We have an open PR for 3D rank filters in scikit-image that should not suffer from the ndimage excessive RAM issue [here](https://github.com/scikit-image/scikit-image/pull/4435). The PR needs review but as I understand it it's ready to go, so you should be able to build that branch locally and try it. It should be much faster than ndimage for large kernels such as the one you are using.

Again, I totally don't understand why dask_image median_filter works at all, given that I can't process even a single chunk with the SciPy version. That is something to discuss in the dask_image issue — I'll add this comment there.

**Comment by GenevieveBuckley** [comment]
Hi @@Sh4zKh4n,

I've read through your thread and will try to respond to all of the points below, so there may be some repetition with what Matt and Juan may have said earlier.

As Matt explains, unless a 3rd party library explicitly claims to support dask arrays, you won't be able to expect them to work well together. This is why you're seeing compute called immediately, the functions you are trying are attempting to coerce the dask array into something they know how to handle like numpy arrays.

For the two libraries you mention by name:
* scipy - the dask-image project implements dask-compatible versions of many of the scipy ndimage functions. You can see a table with a [list of covered functions here](https://github.com/dask/dask-image/issues/152#issuecomment-678841085).
* scikit-image - there is an `skimage.util.apply_parallel()` [function available](https://scikit-image.org/docs/dev/api/skimage.util.html#skimage.util.apply_parallel) which uses dask and `map_overlap` to parallelize computation. Perhaps this is the type of thing you are looking for?

> I went back to dask image and it worked but this time I didnt include it in a function..... So Ive been messing around with data that ultimately could have been run a bit easier...... just tried median from dask_image and didnt put it into a function nor map_blocks....

That's right, dask-image functions implement `map_overlap` for scipy functions, so there's no need to put it inside your own `map_overlap`.

> I chose the median filter, because I couldnt get a uniform or mean filter to run on my data set.

Are you saying that the dask-image `ndfilters.uniform_filter` and `ndfilters.gaussian_filter` didn't work for you, but that the dask-image `ndfilters.median_filter` did work? If that's the case we'd be grateful if you could open a specific issue with a minimal, complete, and verifiable example of the behaviour ([please see here for how to create one](https://stackoverflow.com/help/minimal-reproducible-example)).

**Comment by Sh4zKh4n** [comment]
> Copying over my response from the image.sc forum here, since I really don't understand why `dask_image.ndfilters.median_filter` runs fine while `scipy.ndimage.median_filter`, which it wraps, cannot process even a single chunk. Response with code snippets below. I am just a dask user, not an expert, so corrections from maintainers are very welcome, as well as speculation about what could be different.
> 
> @Sh4zKh4n I recommend that you provide a _complete_ failing example as code (not screenshots) that people can run on their own machine. StackOverflow has a [good article](https://stackoverflow.com/help/minimal-reproducible-example) on this.
> 
> This makes it much easier for people to debug your use case rather than try to think about it just from reading it, which is hard, or have to abstract away the problem.
> 
> In your case, I agree with Matt Rocklin that it seems the ndimage median filter is the failing function. Unfortunately, ndimage just does not do great for large kernel sizes. For example:
> 
> ```
> import numpy as np
> from scipy import ndimage as ndi
> 
> 
> def median3d(image):
>     return ndi.median_filter(image, size=25)
> 
> 
> res = median3d(
>     np.random.randint(0, 256, size=(285, 245, 310)).astype(np.uint8)
> )
> ```
> 
> ie running your code for _just_ one chunk is taking forever on my machine (3min and counting), using up "only" 2GB of RAM. There is an [open issue](https://github.com/scipy/scipy/issues/4878) in SciPy about this excessive RAM usage, but it is really quite a difficult one to fix, which is why it remains open 5 years later.
> 
> Now, the thing I _totally_ don't understand is why `dask_image.ndfilters.median_filter` is working at all for you, since literally [all it is doing](https://github.com/dask/dask-image/blob/cf3bde869be823acc5d2534c2c1c7d2ea4cd8846/dask_image/ndfilters/_order.py#L9-L42) is wrapping `ndimage.median_filter` in a [`map_overlap`](https://docs.dask.org/en/latest/array-overlap.html#dask.array.map_overlap) call. You can see the [source code](https://github.com/dask/dask/blob/d96fed990279fcd272cc5ada005d07c85b104ce5/dask/array/overlap.py#L541) and find that it boils down to [a `map_blocks` call](https://github.com/dask/dask/blob/d96fed990279fcd272cc5ada005d07c85b104ce5/dask/array/overlap.py#L718) just like yours. I can _also_ reproduce that behaviour as follows:
> 
> ```python
> import numpy as np
> from dask_image.ndfilters import median_filter
> from dask.diagnostics import ProgressBar
> 
> pbar = ProgressBar()
> pbar.register()
> 
> arr = da.random.randint(
>     0, 256, size=(10260, 1225, 1550),
>     dtype=np.uint8,
>     chunks=(285, 245, 310)
> )
> 
> smoothed = median_filter(arr, size=25)
> smoothed.to_zarr('smoothed.zarr')
> ```
> 
> ```
> [#                      ] | 3% Completed |  3min 36.8s
> ```
> 
> But, it does eventually start using too much RAM and spilling to disk, and brings my computer to a standstill...
> 
> On that I really must say I am stumped.
> 
> Things I would try next in your situation:
> 
> * try using the [dask.distributed scheduler](https://distributed.dask.org/en/latest/) and some local workers. By default, dask.array uses the threaded scheduler, which as I understand it will request as much RAM as the OS will give, and the OS will give more than it has and spill to disk, which is inefficient. Distributed gives you fine control over the resources you allocate to each worker. We saw that a single chunk takes up about 2GB of RAM to process, so you should be good with e.g. 3 workers with 5GB each (it's good to have a bit of overhead space!).
> * We have an open PR for 3D rank filters in scikit-image that should not suffer from the ndimage excessive RAM issue [here](https://github.com/scikit-image/scikit-image/pull/4435). The PR needs review but as I understand it it's ready to go, so you should be able to build that branch locally and try it. It should be much faster than ndimage for large kernels such as the one you are using.
> 
> Again, I totally don't understand why dask_image median_filter works at all, given that I can't process even a single chunk with the SciPy version. That is something to discuss in the dask_image issue — I'll add this comment there.

**Comment by Sh4zKh4n** [comment]
Sorry for accidentally closing the issue!!! I was trying to cancel the comment sorry!

@jni 

Sorry I should have added a better code snippet, Ill read that article and add. The way I got dask_imag.ndfilters.median  had the same problem when I did the same thing. One of my later comments based on advice from @mrocklin  was that the chunk sizes were too big, I checked the overall size of the output file and chunk sizes by not computing the output result but checking the dask widget for size. So I reduced them even further, and that how I got it to work. It came out very blocky because the blocks werent sharing edges. So I tried that convolve1d function in the z, y and then y direction. It was incredibly slow but it worked as a mean filter. @GenevieveBuckley i havent had a chance to go through all your advice so will reply as I go through and try. Ultimately what I did was I chunked down to chunk sizes as 2MB for a uint8 file but when upfloated this is going to be a chunk of roughly 17MB vs what didnt work which was a chunk of 20MB upfloating to a 173MB file. Which just gets stuck. 

I am making progress as I go along, happy to share if it helps people here? I will try to build a MVCP (?) but is a random array actually appropriate because this is image processing so a structure of some sort might be appropriate.  

To be clear, my over aim is to process 6* of these files which in the end need to be registered and merged. Not one for this, as its not an issue but a how to. I am working my way through it. Because the file sizes are big, I am trying to create masks that I can then use to further reduce the size of the data. I had hoped to rescale the images with scikit image function but kept hitting a wall, what I was trying to do was rescale down to process for masks that were small then rescale up to creat the masks. Unfortunately the rescale function didnt work. I might try striding but ultimately I also will need to process larger file sizes so have been try to get the functions to work. The types of examples I have seen are about deconvolution with dask, which is very cool but the bread and butter I am learning isnt so easy.... Though I am making progress...

small chunk sizes around 2MB got the median filter working for dask_image and all I could tell was the difference was the output was removed according to the docs. 

I hope that makes sense?

**Comment by Sh4zKh4n** [comment]
@GenevieveBuckley  Sorry for the confusion but the guassian has worked for me but when I reduced the chunk size significantly. So they work for small chunk sizes. The up cast the chunk to a float increasing the size significantly so it doesnt work. rechunking the data does though work, chunking to a very small size. Now I think ive made a mistake above and should point out that I did that guassian blur with the chunk size of (285, 245, 310) it works fine. I think the chunk size was when it came to scikit image since it kept upcasting the chunks. The dask guassian blur works fine, I completed it without distributed, I tried that with a kernel with a size (10, 10, 10) and that completed in 36 mins. I did now just try distributed, with guassian blur but kernel (50, 50, 50) but it was a bit hard to tell what was happening. It holds for a while. I went back to without distributed and just feel comfortable when I can see one progress bar. This also seems to hold for while but does actually look like its working. I dont see much spilling to disc looking at task manager and right now its using a total of 6GB ish without using distributed.

```
import numpy as np
from dask_image.ndfilters import median_filter
from dask.diagnostics import ProgressBar

pbar = ProgressBar()
pbar.register()

arr = da.random.randint(
    0, 256, size=(10260, 1225, 1550),
    dtype=np.uint8,
    chunks=(285, 245, 310)
)

smoothed = guassian_filter(arr, size=25)
smoothed.to_zarr('smoothed.zarr')

```

This seems to be working fine.

**Comment by Sh4zKh4n** [comment]
@jni 

```
import numpy as np
from dask_image.ndfilters import median_filter
from dask.diagnostics import ProgressBar

pbar = ProgressBar()
pbar.register()

arr = da.random.randint(
    0, 256, size=(10260, 1225, 1550),
    dtype=np.uint8,
    chunks=(285, 245, 310)
)

# load/import classes
from dask.distributed import Client

# set up cluster and workers
client = Client(n_workers=3, 
                threads_per_worker=1,
                memory_limit='4GB')

# have a look at your workers
client


smoothed = guassian_filter(arr, size=(50,50,50))
smoothed.to_zarr('smoothed.zarr')
```
This is very strange, I interrupted the run I was doing with the guassian blur and decided to run the distributed with your suggestion but I ran with 3 workers and 4GB each. The workers arent taking up all that much space but its spilling to disc but its running... slowly.  much slower than without distributed?

**Comment by GenevieveBuckley** [comment]
> I am making progress as I go along, happy to share if it helps people here?

I'm glad you're making progress on your work, and no it's not necessary to share updates here :)

**Comment by Sh4zKh4n** [comment]
@GenevieveBuckley  the table is really helpful and thanks for getting a PR going on the docs. I think its time to close the issue.
