### ISSUE TITLE
Add function covereage table to the documentation

### ISSUE THREAD

**Issue by GenevieveBuckley** [dask/dask-image#154]
It would be good to add a page to our docs including this table comparing coverage of dask-image vs scipy ndimage functions.

| Function name                 | SciPy ndimage | dask-image |
|-------------------------------|---------------|------------|
| `affine_transform`            | X             |            |
| `binary_closing`              | X             | X          |
| `binary_dilation`             | X             | X          |
| `binary_erosion`              | X             | X          |
| `binary_fill_holes`           | X             |            |
| `binary_hit_or_miss`          | X             |            |
| `binary_opening`              | X             | X          |
| `binary_propagation`          | X             |            |
| `black_tophat`                | X             |            |
| `center_of_mass`              | X             | X          |
| `convolve`                    | X             | X          |
| `convolve1d`                  | X             |            |
| `correlate`                   | X             | X          |
| `correlate1d`                 | X             |            |
| `distance_transform_bf`       | X             |            |
| `distance_transform_cdt`      | X             |            |
| `distance_transform_edt`      | X             |            |
| `extrema`                     | X             | X          |
| `find_objects`                | X             |            |
| `fourier_ellipsoid`           | X             |            |
| `fourier_gaussian`            | X             | X          |
| `fourier_shift`               | X             | X          |
| `fourier_uniform`             | X             | X          |
| `gaussian_filter`             | X             | X          |
| `gaussian_filter1d`           | X             |            |
| `gaussian_gradient_magnitude` | X             | X          |
| `gaussian_laplace`            | X             | X          |
| `generate_binary_structure`   | X             |            |
| `generic_filter`              | X             | X          |
| `generic_filter1d`            | X             |            |
| `generic_gradient_magnitude`  | X             |            |
| `generic_laplace`             | X             |            |
| `geometric_transform`         | X             |            |
| `grey_closing`                | X             |            |
| `grey_dilation`               | X             |            |
| `grey_erosion`                | X             |            |
| `grey_opening`                | X             |            |
| `histogram`                   | X             | X          |
| `imread`                      | X             | X          |
| `iterate_structure`           | X             |            |
| `label`                       | X             | X          |
| `labeled_comprehension`       | X             | X          |
| `laplace`                     | X             | X          |
| `map_coordinates`             | X             |            |
| `maximum`                     | X             | X          |
| `maximum_filter`              | X             | X          |
| `maximum_filter1d`            | X             |            |
| `maximum_position`            | X             | X          |
| `mean`                        | X             | X          |
| `median`                      | X             | X          |
| `median_filter`               | X             | X          |
| `minimum`                     | X             | X          |
| `minimum_filter`              | X             | X          |
| `minimum_filter1d`            | X             |            |
| `minimum_position`            | X             | X          |
| `morphological_gradient`      | X             |            |
| `morphological_laplace`       | X             |            |
| `percentile_filter`           | X             | X          |
| `prewitt`                     | X             | X          |
| `rank_filter`                 | X             | X          |
| `rotate`                      | X             |            |
| `shift`                       | X             |            |
| `sobel`                       | X             | X          |
| `spline_filter`               | X             |            |
| `spline_filter1d`             | X             |            |
| `standard_deviation`          | X             | X          |
| `sum`                         | X             | X          |
| `uniform_filter`              | X             | X          |
| `uniform_filter1d`            | X             |            |
| `variance`                    | X             | X          |
| `watershed_ift`               | X             |            |
| `white_tophat`                | X             |            |
| `zoom`                        | X             |            |

**Comment by abhisht51** [comment]
Hi, Do i just add this table to the doc ?

**Comment by GenevieveBuckley** [comment]
> Hi, Do i just add this table to the doc ?

I'd say so!

We have all our documentation pages in the `docs/` folder of this repository, and use ReST ([restructured text](https://thomas-cokelaer.info/tutorials/sphinx/rest_syntax.html)) formatting.

**Comment by Sh4zKh4n** [comment]
Hi, I think this is great but maybe it would be worth making clear whether the table shows in the ndimage table x mark means it works with dask_image or if ndimage has the function? Sorry to be a pain. I think its a great table but a little add would help in explanation for naive users like myself

**Comment by abhisht51** [comment]
hi @GenevieveBuckley  I have issue a PR, please review it

**Comment by GenevieveBuckley** [comment]
> Hi, I think this is great but maybe it would be worth making clear whether the table shows in the ndimage table x mark means it works with dask_image or if ndimage has the function? Sorry to be a pain. I think its a great table but a little add would help in explanation for naive users like myself

@Sh4zKh4n `scipy.ndimage` has all of the functions listed (you'll see a cross marker in every row of the scipy column). However `dask-image` only supports a subset of these, so you see only some of the functions are marked with a cross in the dask-image column.

**Comment by GenevieveBuckley** [comment]
Closed via https://github.com/dask/dask-image/pull/155
