### ISSUE TITLE
Failing tiff imread tests

### ISSUE THREAD

**Issue by GenevieveBuckley** [dask/dask-image#160]
It looks like our imread test are failing, as shown by the CI for this unrelated PR https://github.com/dask/dask-image/pull/159

Here's a link to the output of one of the CI jobs showing this failure:
https://app.circleci.com/pipelines/github/dask/dask-image/49/workflows/9b4326b7-fc8a-433f-ac0c-ce36cc344e7f/jobs/1315

**Comment by jakirkham** [comment]
Based on the failure, it seems `nframes` isn't being respected when chunking the data.
