### ISSUE TITLE
DOCS: Update information in AUTHORS.rst

### ISSUE THREAD

**Issue by GenevieveBuckley** [dask/dask-image#166]
This is another good first issue.

The dask-image website has a [page to acknowledge contributors](http://image.dask.org/en/latest/authors.html), but it's not kept up to date.

1. We should edit [this file](https://github.com/dask/dask-image/blob/master/AUTHORS.rst) and replace the line "None yet. Why not be the first?" with something like "See the full list of contributors here" and a link to https://github.com/dask/dask-image/graphs/contributors
2. We should also remove John's old email address from this page, he stopped working for Janelia a while ago. I'm pretty sure it no longer works. Optionally, if @jakirkham wants to suggest replacing it with a different public email address, we could do that here too.

**Comment by feiming** [comment]
i'm working on it

**Comment by feiming** [comment]
should I replace John's email address @jakirkham  instead?

**Comment by feiming** [comment]
https://github.com/dask/dask-image/pull/167

**Comment by feiming** [comment]
is this part of a hacktoberfest?

**Comment by GenevieveBuckley** [comment]
> is this part of a hacktoberfest?

I put this up in anticipation for the [sprint this weekend](https://github.com/dask/dask-image/issues/163) (which you are also welcome to join!).

Are you doing Hacktoberfest? I guess we could try and make this count towards it, I think it's just a matter of adding a specific label?

**Comment by GenevieveBuckley** [comment]
Closed via https://github.com/dask/dask-image/pull/167
