### ISSUE TITLE
Drop slicerator CI install hack (once fixed)

### ISSUE THREAD

**Issue by jakirkham** [dask/dask-image#17]
_From @jakirkham on June 7, 2017 20:3_

We had to add a hack for the CIs in commit ( https://github.com/dask-image/dask-imread/commit/ffd6cc5bb40fa24d7652520d0598fa71b87331e4 ) to `pip` install `slicerator` in addition to `conda` installing it as `pip` could not recognize that it was already installed. This seems to be some consequence of the choice to use Python modules and not a Python package to hold the library content.

Have proposed a fix upstream in PR ( https://github.com/soft-matter/slicerator/pull/26 ), which seems to resolve the issue. Once upstream merges that fix and releases, we should drop this hack. Though admittedly that will hinge on dropping Python 3.4 as we won't have a new Python 3.4 package to work with from `conda-forge`.

_Copied from original issue: dask-image/dask-imread#7_

**Comment by jakirkham** [comment]
Some discussion on the new `slicerator` release in issue ( https://github.com/soft-matter/slicerator/issues/35 ).

**Comment by jakirkham** [comment]
This should be possible now that there is a 1.0.0 release.

**Comment by GenevieveBuckley** [comment]
This issue can be closed now. 
The minimum version of slicerator used anywhere in this repo is v1.0.0, and I can't see this install hack anywhere either (probably was removed a long time ago)
