### ISSUE TITLE
Migrate CI to GitHub Actions

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/dask-image#178]
Due to changes in the Travis CI billing, the Dask org is migrating CI to GitHub Actions.

This repo contains a `.travis.yml` file which needs to be replaced with an equivalent `.github/workflows/ci.yml` file.

It also appears that this repo uses CircleCI and AppVeyor in addition to Travis. Perhaps we should consider consolidating under GitHub Actions.

See dask/community#107 for more details.

**Comment by GenevieveBuckley** [comment]
Thank you for the heads up!

**Comment by GenevieveBuckley** [comment]
I'd say this is the TODO list for this repository:

- [ ] Turn our conda .yml files into the equivalent text requirement files (can be pip installed into conda environments, or used directly in the CI)
- [ ] Create a github action for push/pull requests. Matrixed over python 3.6, 3.7, 3.8, and for Linux, Mac, & Windows.
- [ ] Add a testing step to the new release github action: https://github.com/dask/dask-image/pull/175
- [ ] Update the README build badge, as described by https://github.com/dask/community/issues/107#issuecomment-720526856
- [ ] Update the documentation on how to create test environments locally to CONTRIBUTING.rst (sorry Kuya-san)
- [ ] Create a scheduled action to run tests(?) This repository often goes long-ish stretches without much activity and Gen is sick of finding out just before a conference that something broke the tests in the last couple of months. https://github.com/dask/dask-image/pull/173

**Comment by GenevieveBuckley** [comment]
It's a pity the Travis announcement didn't come a few days *before* the SciPy Japan sprint...

**Comment by GenevieveBuckley** [comment]
This comment makes a good point: https://github.com/dask/community/issues/107#issuecomment-720555156

> > Each job has options such as OS selection and the option to specify a matrix.
> 
> A note of light caution -- currently if you have a matrix of say Python versions and OS in the same workflow file, if one of those matrix entries failed you can't restart it individually, you have to trigger a full re-run of everything defined in that file. On xonsh we've subsetted them into one os per workflow file so we can at least individually restart Windows runs or MacOS runs

**Comment by jacobtomlinson** [comment]
> Create a scheduled action to run tests(?)

**Comment by GenevieveBuckley** [comment]
I've been meaning to do this but never quite getting around to it.

However, the current Travis CI page is now also showing this warning (so we'll have to fix something soon): *"Please be aware travis-ci.org will be shutting down in several weeks, with all accounts migrating to travis-ci.com. Please stay tuned here for more information."*
