### ISSUE TITLE
API docs include unreleased dask_image.ndinterp package 

### ISSUE THREAD

**Issue by forman** [dask/dask-image#180]
First of all, happy new year and thanks for this great project!

Latest API docs describe the [dask_image.ndinterp](https://dask-image.readthedocs.io/en/latest/dask_image.ndinterp.html), however, version 0.4 does not include this package yet. 

We find `dask_image.ndinterp.affine_transform` extremely useful (@m-albert, thanks for implementing) for spatial resampling of Earth observation data in our xcube project, see [#391](https://github.com/dcs4cop/xcube/issues/391). 

Therefore we currently use a dask-image source install from master. When can we expect version 0.5 as conda package?

**Comment by m-albert** [comment]
@forman Glad to hear `dask_image.ndinterp.affine_transform` is useful to you :)

Actually, a project of mine would also benefit from having `ndinterp` included in a release.

**Comment by jni** [comment]
@GenevieveBuckley is starting up full time in Feb as Dask Life Sciences Fellow so I suspect she'll be able to cut a release then. =)

I haven't found a *great* solution for versioned docs out there. Would be very happy to see people provide suggestions...

**Comment by wtbarnes** [comment]
Just wanted to chip in and say we are very interested in using `affine_transform` in sunpy as well (sunpy/sunpy#3266) and we would benefit from a release of `dask-image` with this functionality.

**Comment by dstansby** [comment]
> I haven't found a _great_ solution for versioned docs out there. Would be very happy to see people provide suggestions...

Sorry for interrupting, but I noticed this in passing. It looks like http://image.dask.org/ is redirecting to the "latest" version of the docs, which is what is on master and not what is released. You should be able to change the default in the readthedocs settings to point to "stable", which means by default users will see documentation for the last released version of the package.

**Comment by forman** [comment]
> You should be able to change the default in the readthedocs settings to point to "stable", 

Sorry, no, [stable](http://image.dask.org/en/stable/dask_image.ndinterp.html) gives "page not found".

**Comment by dstansby** [comment]
For `ndinterp` that's because it hasn't been released yet. http://image.dask.org/en/stable/ works

**Comment by GenevieveBuckley** [comment]
Happy new year! Juan is right, I'm still on vacation right now. Remind me here again in the second week of February if you haven't heard anything before then.

It's great to see so much interest in @m-albert's work :)

**Comment by GenevieveBuckley** [comment]
The [pre-release is now available](https://github.com/dask/dask-image/releases)!

You can test it using `pip install --pre dask-image`

I'd be very grateful if anyone is able to test it out. If we don't discover any problems in the next 24 - 48 hours, I'll release the official version 0.5.0

**Comment by jakirkham** [comment]
Looks like PyPI may have dropped the `rc1` (unless I'm missing something). Should we fix it or just let it be shipped? If we go for the latter, we can always fix any issues after and cut a patch release.

https://pypi.org/project/dask-image/0.5.0/

**Comment by GenevieveBuckley** [comment]
> Looks like PyPI may have dropped the rc1 (unless I'm missing something). 

You're not missing anything @jakirkham - I made a mistake and forgot to include `rc1` in the tag. 

> Should we fix it or just let it be shipped? If we go for the latter, we can always fix any issues after and cut a patch release.

I'm happy to just let it be shipped. As you say, we can always make a patch release if there are any issues.

**Comment by GenevieveBuckley** [comment]
Ok, dask-image 0.5.0 is available!

How to install:
* `pip install dask-image==0.5.0` https://pypi.org/project/dask-image/0.5.0/
* `conda install dask-image=0.5.0 -c conda-forge` (might need to wait a few hours for conda-forge to "see" the new release, but it's been approved here https://github.com/conda-forge/dask-image-feedstock/pull/7)

Please try it out & open an issue if you run into any problems.

**Comment by jakirkham** [comment]
Thanks Genevieve! 😄

**Comment by forman** [comment]
@GenevieveBuckley, thanks 👍
