### ISSUE TITLE
Move default branch from "master" -> "main"

### ISSUE THREAD

**Issue by jsignell** [dask/dask-image#184]
@jrbourbeau and I are in the process of moving the default branch for this repo from master to main. 

 - [x] Changed in GitHub
 - [x] Merged PR to change branch name in code.(https://github.com/dask/dask-image/pull/185)

### What you'll see
Once the name on github is changed (the first box above is Xed, or this issue closed), when you try to `git pull` you'll get 

```bash
Your configuration specifies to merge with the ref 'refs/heads/master'
from the remote, but no such ref was fetched.
```

### What you need to do

First: **head to your fork and rename the default branch there**
Then:
```bash
git branch -m master main
git fetch origin
git branch -u origin/main main
```

**Comment by GenevieveBuckley** [comment]
Ok, I've renamed the default branch to "main" and merged your pull request @jsignell 

Would you like to leave this issue open for a few more days so other developers have a chance to see it and make the switch in their local respositories?

**Comment by jrbourbeau** [comment]
Thanks @GenevieveBuckley! 

> Would you like to leave this issue open for a few more days so other developers have a chance to see it and make the switch in their local respositories?

FWIW we've been closing them immediately in other repositories in the Dask org, but leaving open for other developers is also totally reasonable

**Comment by GenevieveBuckley** [comment]
Ok, then we might as well close it here too.

FYI @m-albert @jni @jakirkham
