### ISSUE TITLE
Array types incompatible error in convolve. 

### ISSUE THREAD

**Issue by Shaunakde** [dask/dask-image#187]
I am trying to use the `convolve` function from the `dask_image` library. No matter what combination of inputs I try, I seem to keep running into the same error. 

My inputs are `dcube`:

```
<xarray.DataArray 'A' (time: 2, y: 823, x: 1296)>
array([[[330., 226., 709., ..., 135.,  82.,  76.],
        [125., 615., 293., ..., 156., 207., 127.],
        [126., 506., 218., ..., 228., 240., 179.],
        ...,
        [ 73., 137., 145., ..., 375., 453., 542.],
        [ 86.,  78., 148., ..., 321., 227., 619.],
        [ 88., 155.,  42., ..., 262., 279., 518.]],

       [[330., 226., 709., ..., 135.,  82.,  76.],
        [125., 615., 293., ..., 156., 207., 127.],
        [126., 506., 218., ..., 228., 240., 179.],
        ...,
        [ 73., 137., 145., ..., 375., 453., 542.],
        [ 86.,  78., 148., ..., 321., 227., 619.],
        [ 88., 155.,  42., ..., 262., 279., 518.]]])
Coordinates:
    pol      <U2 'HH'
  * y        (y) float64 3.653e+06 3.653e+06 3.653e+06 ... 3.652e+06 3.652e+06
  * x        (x) float64 1.047e+06 1.047e+06 1.047e+06 ... 1.049e+06 1.049e+06
  * time     (time) datetime64[ns] 2020-11-24T22:24:50 2020-11-18T01:15:05
Attributes:
    orbit:       A
    transform:   (1.1987408006010196, 0.0, 1047472.9120438152, 0.0, -1.198740...
    crs:         {'proj': 'utm', 'zone': 10, 'datum': 'WGS84', 'units': 'm', ...
```

and a `patch`:

```
filter_wt =  (1 / (N * N)) * np.ones((N, N),dtype='float64')
>> array([[0.11111111, 0.11111111, 0.11111111],
       [0.11111111, 0.11111111, 0.11111111],
       [0.11111111, 0.11111111, 0.11111111]])
```

When I try to use the `convolve` function as follows:
```
from dask_image.ndfilters import convolve
convolve(dcube[0], xr.DataArray(filter_wt), mode='constant', cval=0.0).compute()
```
I end up with this error:
```*** ValueError: Array types must be compatible.```

Even though, DaskArray with a numpy backend and a numpy array should be compatible. To get around this, I tried initializing both as dask arrays:
```
(Pdb) convolve(da.from_array(dcube[i]), da.from_array(filter_wt), mode='constant', cval=0.0).compute()
*** ValueError: Array types must be compatible.
```

```
(Pdb) type(da.from_array(dcube[0]))
<class 'dask.array.core.Array'>
(Pdb) type(da.from_array(filter_wt))
<class 'dask.array.core.Array'>
```

Any instructions on why casting both to ask arrays didn't work would be very helpful!

**Comment by GenevieveBuckley** [comment]
Hi @Shaunakde 

If you have xarray chunks in `dcube`, I think you should try to make `patch` an xarray as well, then try it. (Alternatively, you could also try to make the chunks in `dcube` numpy arrays, to match the `patch` numpy array). Does that help things?

**Comment by GenevieveBuckley** [comment]
Here's the backstory on why it works this way. I'm open to any suggested improvements you have.

When I started introducing GPU support to `dask-image` we needed a way to prevent mixing of cupy arrays with other array types which do not live on the GPU (because that will cause an error). So, I made a quick check to try and prevent that:

https://github.com/dask/dask-image/blob/5afde9ac8241ae46971ad9a56d2f559e86c0250c/dask_image/dispatch/_utils.py#L10-L25

The check isn't very sophisticated.
* For dask arrays, it finds the array type of each dask chunk
* For non-dask arrays, it finds the type of the array.

Those two things need to match to be called "compatible".

https://github.com/dask/dask-image/blob/5afde9ac8241ae46971ad9a56d2f559e86c0250c/dask_image/dispatch/_dispatcher.py#L6-L12

It's not clever enough to know that xarrays are based on numpy arrays, so that should also be fine. If there's an easy way to allow that but also keep the cupy GPU check we need, that would be a welcome change.

**Comment by Shaunakde** [comment]
> Hi @Shaunakde
> 
> If you have xarray chunks in `dcube`, I think you should try to make `patch` an xarray as well, then try it. (Alternatively, you could also try to make the chunks in `dcube` numpy arrays, to match the `patch` numpy array). Does that help things?

Thanks for responding to this. I tried setting them both to xarrays, but ran into an error that `xarray doesn't have map_blocks`. That's why I assumed that the two must be dask arrays? One suggestion I have is to provide an override flag for this check. But I am not sure I'm actually using dask/xarray correctly!

**Comment by Shaunakde** [comment]
Okay, managed to set up a small working example:

Imports:
```
import dask_image.ndfilters as ndf
import dask.array as da
import xarray as xr
import numpy as np
```
Patch `numpy`:
```
patch = 1/9 * np.ones((3,3))
ndf.convolve(image, patch)
```

Output:
```
ValueError: Array types must be compatible.
```

Both DataArrays:
```
patch = xr.DataArray( 1/9 * np.ones((3,3)), dims=['x','y'], coords={'x':range(3), 'y':range(3)})
image = xr.DataArray(np.random.random((100,100)), dims=['x','y'], coords={'x':range(100),'y':range(100)})
```
Output:
```
ndf.convolve(image, patch)
>> AttributeError: 'DataArray' object has no attribute 'map_overlap'
```

Both DaskArrays:
```
patch = da.from_array( 1/9 * np.ones((3,3)))
image = da.from_array(image)
```

Output:
```
ValueError: Array types must be compatible.
```
The reason this is failing is probably that one is a `ndarray` and the other is a `xarray.DataArray`. So, if I convert as so:

```
image = da.from_array(image.values)
```

Which works! But, I do think we can probably make the documentation more helpful + find a way of "meshing" the datatypes.

**Comment by GenevieveBuckley** [comment]
> Thanks for responding to this. I tried setting them both to xarrays, but ran into an error that `xarray doesn't have map_blocks`. That's why I assumed that the two must be dask arrays? One suggestion I have is to provide an override flag for this check.

The first argument must be a dask array, yes. Your other array inputs (in this case `patch`) must match the type of array stored in the dask array chunks of your first argument (`dcube`).

Examples of compatible arrays: 
* Two (or more) dask arrays with numpy chunks
* A dask array with numpy chunks, and a numpy array 
  
Examples of incompatible arrays: 
* A numpy array and a cupy array 
* A numpy array and an xarray.DataArray

> The reason this is failing is probably that one is a `ndarray` and the other is a `xarray.DataArray`. As you mention that the check is discovering that one of the chunks is `ndarray` and the other is `xarray`.

Yes, this is a good summary.

**Comment by GenevieveBuckley** [comment]
I'm going to close this issue now since it seems like the problem has been resolved.

For anyone reading, we'd be very happy to accept a pull request aimed at making the documentation clearer & more helpful for this particular problem. I think that's a very good idea.
