### ISSUE TITLE
"wrap" mode for label

### ISSUE THREAD

**Issue by rabernat** [dask/dask-image#189]
Over in https://github.com/scipy/scipy/issues/8218 we are discussing how to implement "wrap" mode (i.e. periodic boundary conditions) for `label` and other morphological functions. (This issue is just about `label`.) We would like to be able to call `label` and have features that cross the array's periodic boundary (in our case, the date line), be counted as a single feature.

I'm opening this issue because
1. If implemented, we would eventually want to propagate this feature downstream to dask-image
2. It strikes me that you have essentially _already implemented it_! Dask-image is able to automatically unify labels across neighbor chunks. This code seems to live in https://github.com/dask/dask-image/blob/main/dask_image/ndmeasure/_utils/_label.py. For "wrap" mode, we could apply basically the same approach, but treating the array as its _own neighbor chunk_.

It sounds like the scipy-devs are open to accepting a PR to implement wrap-mode via a relabeling approach. So I am wondering if you folks here have any advice about how to best extract / adapt your relabeling method to live in scipy itself. Thanks in advance for any advice or hints you might be able to share.

And thanks for the amazing dask-image package! It is super helpful for all our work.

cc @hscannell

**Comment by jakirkham** [comment]
cc @jni

**Comment by GenevieveBuckley** [comment]
@jni authored https://github.com/dask/dask-image/blob/main/dask_image/ndmeasure/_utils/_label.py so I'd say he's probably the best person to guide you.

**Comment by jakirkham** [comment]
cc @grlee77 (also in case you have thoughts on how we might consolidate this upstream)

**Comment by jni** [comment]
Hi everyone,

I'm sorry that I haven't had the bandwidth to respond here properly, much less consider the code carefully. I do love that code, which @jakirkham and I implemented over a feverish couple of days in 2019 here in Melbourne — remember in-person visits?

Anyway, I think your assessment is right @rabernat, the very same code can almost certainly be used to wrap the arrays, modulo some connectivity parameter. It'd be equally fun to implement, should someone have the bandwidth. I'd love to say I would do it but realistically I won't get the chance any time soon.

**Comment by Holmgren825** [comment]
Hey,
This is a bit old now but came across it looking for a way to wrap features over the date line in gridded geodata (Similar use to @rabernat I believe). I've managed to hack together an initial solution which merges features across the boundaries of the array. Would be happy to discuss further and try to get it up to standards if there is still some interest in this.

**Comment by jakirkham** [comment]
Thanks Erik! 🙏

Maybe it is worth opening a PR to discuss the changes?

**Comment by Holmgren825** [comment]
Sounds good! See #344.

**Comment by m-albert** [comment]
Closed by https://github.com/dask/dask-image/pull/344.
