### ISSUE TITLE
Add alias 'gaussian' to point towards 'gaussian_filter' in ndfilters

### ISSUE THREAD

**Issue by GenevieveBuckley** [dask/dask-image#192]
I'd like an alias added so that `gaussian` also points to `gaussian_filter` in the ndfilters subpackage.

**Comment by K-Monty** [comment]
Hi! I am looking for a good first contribution. Can I try on this issue?

**Comment by GenevieveBuckley** [comment]
Go for it @K-Monty!

**Comment by K-Monty** [comment]
I have just tried it @GenevieveBuckley ! :) But not sure if this is what's requested: https://github.com/dask/dask-image/pull/193

**Comment by GenevieveBuckley** [comment]
Great! I'll take a look in the next couple of days @K-Monty

**Comment by GenevieveBuckley** [comment]
It occurs to me that I should probably check with @jakirkham for objections first.

Why I wanted to do this:
* I'm lazy and don't like typing
* I often switch between using scikit-image and dask-image
```python
from skimage.filters import gaussian
# ... so I often try to do this...
from dask_image.ndfilters import gaussian  # nope, need to import 'gaussian_filter'
```

But I did not consider:
* Whether the added complexity in the API is a bad thing. (I don't *think* it outweighs the extra convenience, but I'd like other people's opinions here).

**Comment by jakirkham** [comment]
The main thing that comes to mind is this line from The Zen of Python, "There should be one-- and preferably only one --obvious way to do it." ( https://www.python.org/dev/peps/pep-0020/ )

That said, I think I understand what's being asked here. To try rephrase more broadly, could we make it easier for people coming from scikit-image and its structure/naming/... to use dask-image? I think the answer is yes. Though we might want to think about how we do that generally (and then hopefully the answer for this use case comes out of that).

Some thoughts on how we might approach this:

1. Add aliases to existing modules (like what is currently proposed)
2. Provide interfaces that match common naming schemes (`dask_image.scipy`, `dask_image.skimage`, etc.)
3. Enable some kind of dispatching inside scikit-image to call the appropriate dask-image function
4. ...

Thoughts? 🙂

**Comment by jakirkham** [comment]
cc @jni (in case you have thoughts on this as well)

**Comment by GenevieveBuckley** [comment]
Thoughts: 

>     1. Add aliases to existing modules (like what is currently proposed)

I'm happy to do this in cases where it's likely to be a common irritation.

Looking at this another way: there is already one way to call a gaussian filter in `scikit-image`, and another way to do it in `scipy.ndimage`/`dask-image`. The current situation is not exactly "there is one obvious way to do it" anyway.

>     2. Provide interfaces that match common naming schemes (`dask_image.scipy`, `dask_image.skimage`, etc.)

I do not think we can commit to this, it seems unfeasible to me.

>     3. Enable some kind of dispatching inside scikit-image to call the appropriate dask-image function

This is a much better idea than 2. You could have 1 and 3 together if you wanted, or separately. I think our recent conversation with Juan & Greg was promising.
