### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by GenevieveBuckley** [dask/dask-image#196]
We should make a release for dask-image 0.5.1 to address https://github.com/dask/dask-image/issues/194. There's no special urgency here (that particular bug has an easy workaround), so let's plan to make the release sometime within the next 4 weeks.

This would be a good release for @m-albert to do. The [release guide is here](https://github.com/dask/dask-image/tree/main/docs/release). I expect we'll find some things to edit/improve in the guide as we go.

**Comment by GenevieveBuckley** [comment]
I'd forgotten - GPU support for the `ndmorph` subpackage is one other major change since the last release https://github.com/dask/dask-image/pull/157 

That migh mean the new release should be named 0.6.0

**Comment by GenevieveBuckley** [comment]
I wasn't able to reproduce the error (using Linux instead of Windows), but here's another (possible?) bug that appears to be fixed by the current master branch: https://github.com/dask/dask-image/issues/200

**Comment by GenevieveBuckley** [comment]
And now all the local cupy tests are failing, gah :(
This is frustrating, I don't think all that much can have changed since March https://github.com/dask/dask-image/issues/190

**Comment by m-albert** [comment]
@GenevieveBuckley Hmm what type of errors are you getting?

**Comment by GenevieveBuckley** [comment]
> @GenevieveBuckley Hmm what type of errors are you getting?

Turns out, the kind of errors that are because my *entire* cupy installation is broken. 
Good news: maybe there isn't something wrong with dask-image. 
Bad news: everything is broken again for me personally.

**Comment by GenevieveBuckley** [comment]
There was something wrong with my NVIDIA drivers (thanks to help from the RAPIDS slack channel, that was great). I've wiped and reinstalled as many as I could, and that seems to have done the trick.

Note: I did find and fix this bug along the way, so I think it was helpful https://github.com/dask/dask-image/pull/206

**Comment by m-albert** [comment]
Sorry you had to go through reinstalling NVIDIA drivers, I did have some painful experiences with that in the past!

Great that there's no general problem and that you even found a bug along the way.

**Comment by GenevieveBuckley** [comment]
I do want to look at https://github.com/dask/dask-image/pull/205 and try to include that in the release too, if it's quick

**Comment by m-albert** [comment]
> I do want to look at #205 and try to include that in the release too, if it's quick

Should be quick!

**Comment by GenevieveBuckley** [comment]
It's out! 

https://github.com/dask/dask-image/releases/tag/v0.6.0

Still need to wait for the conda-forge bot to pick up the change & make a PR for us over at [the dask-image feedstock](https://github.com/conda-forge/dask-image-feedstock). When that's merged, people will be able to conda install the new release too.

**Comment by GenevieveBuckley** [comment]
> Still need to wait for the conda-forge bot to pick up the change & make a PR for us over at [the dask-image feedstock](https://github.com/conda-forge/dask-image-feedstock). When that's merged, people will be able to conda install the new release too.

@m-albert you're welcome to merge the PR the bot makes for us, if you like.

**Comment by m-albert** [comment]
> @m-albert you're welcome to merge the PR the bot makes for us, if you like.

Great, done :) Thanks for making the release @GenevieveBuckley!
