### ISSUE TITLE
Rename `scipy.ndimage.sum` to `scipy.ndimage.sum_labels`

### ISSUE THREAD

**Issue by jakirkham** [dask/dask-image#209]
Recently SciPy 1.6.0 changed the name of this API. For reference, please see PR ( https://github.com/scipy/scipy/pull/12242 ). Note the old name is still around as an alias

**Comment by jakirkham** [comment]
CuPy is also looking at making this change ( https://github.com/cupy/cupy/issues/5111 )

**Comment by GenevieveBuckley** [comment]
@jakirkham does [PR 172](https://github.com/dask/dask-image/pull/172) address your issue, or do you mean something else here?

**Comment by jakirkham** [comment]
Partially. The other part is CuPy is making this change. So we would want to update the dispatching to CuPy to use the new name

**Comment by grlee77** [comment]
I opened cupy/cupy#5200 for this. Hopefully it will get included in the 9.1 release. 

I don't think there is anything else to do here on the `dask-image` side, so the issue can probably be closed.

**Comment by jakirkham** [comment]
Yeah I think both of you are right. Nothing to do here. Closing...
