### ISSUE TITLE
CalVer

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-image#214]
Should this repository shift to calendar versioning?

Many other Dask projects have moved.  It also helps avoid the "when do we claim 1.0" question

**Comment by GenevieveBuckley** [comment]
I have no big preference either way. @jakirkham?

**Comment by GenevieveBuckley** [comment]
Ok, that means we need a PR updating the release guide section on "Determining the new version number".

That file is here: https://github.com/dask/dask-image/blob/main/docs/release/release_guide.rst

**Comment by GenevieveBuckley** [comment]
We'll also add a link to https://calver.org/
