### ISSUE TITLE
Updating authors

### ISSUE THREAD

**Issue by jakirkham** [dask/dask-image#223]
Currently [this file]( https://github.com/dask/dask-image/blob/main/AUTHORS.rst ) lists only me. However other people have been contributing here. It would be great to have a more comprehensive list.

Also other projects tend to call this `CONTRIBUTORS.txt`. I think `AUTHORS.rst` just came from a Python project template tool. So it might be worth renaming.

Independently some of the source files have `__author__` and `__email__`. The email referenced is dead and as already noted we have more people contributing. We might want to strip these out.

Not sure what other relevant changes we might want to include, but feel free to suggest.

**Comment by GenevieveBuckley** [comment]
1. I absolutely do not want to spend time maintaining an author/contributor list by hand. I thought linking to the contributors page on github would be a good way around that? https://github.com/dask/dask-image/issues/166

2. I don't mind what this file is called. To be honest, I don't mind whether this file exists at all, since this information is easily available at https://github.com/dask/dask-image/graphs/contributors

3. Yes, stripping out `__author__` and `__email__` sounds like a good idea. Even aside from the fact these things go out of date,  the implication an email might be required is a real disincentive to contribute (why would anyone want to hand strangers more avenues to potentially harass them?)

**Comment by grlee77** [comment]
Just relying on the GitHub contributors page is also be fine by me. From the command line, one can run something like `git shortlog --summary --numbered --email` to get similar info.

**Comment by jakirkham** [comment]
> I absolutely do not want to spend time maintaining an author/contributor list by hand. I thought linking to the contributors page on github would be a good way around that?

I thought we could ask people to add themselves. We do this in Zarr for example. That said, I don't feel strongly about it. Some people do like the credit though

**Comment by GenevieveBuckley** [comment]
> I thought we could ask people to add themselves.

That was the original situation here too, but no-one ever updated that file. 

> That said, I don't feel strongly about it. Some people do like the credit though

Sure, some people do like credit. I'm happy to highlight the github contributors page, I think that fills this function. 

I'm more worried about creating only crediting some contributors & not others with a manually updated list. That feels more fraught.

**Comment by GenevieveBuckley** [comment]
Ok, I'll make a PR to remove the `__author__` and `__email__` lines.

Your old email address still appears in the setup.py file, not sure if you want that changed to something else @jakirkham 
https://github.com/dask/dask-image/blob/16687e5ac1f0476bcfa19016aa41a6fa8993dc04/setup.py#L58

**Comment by jakirkham** [comment]
> Your old email address still appears in the setup.py file, not sure if you want that changed to something else @jakirkham

Feel free to drop that one as well. Would much rather users come to GitHub than email

The author field can probably be made more inclusive like `"dask-image contributors"` or similar

**Comment by GenevieveBuckley** [comment]
Ok, done

**Comment by jakirkham** [comment]
> > I thought we could ask people to add themselves.
> 
> That was the original situation here too, but no-one ever updated that file.
> 
> > That said, I don't feel strongly about it. Some people do like the credit though
> 
> Sure, some people do like credit. I'm happy to highlight the github contributors page, I think that fills this function.
> 
> I'm more worried about creating only crediting some contributors & not others with a manually updated list. That feels more fraught.

Yeah that makes sense. If people are not doing this themselves, then agree we shouldn't try to maintain the list ourselves.
