### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by thewtex** [dask/dask-image#269]
Hi @GenevieveBuckley @jakirkham !

Checking into the scipy API warnings described at https://github.com/spatial-image/multiscale-spatial-image/issues/58, they are resolved with `dask-image` `main`. Is it possible to cut a new release? :pray:

**Comment by GenevieveBuckley** [comment]
Release in progress now :)

Link to the fix for the scipy deprecations:
* Issue: https://github.com/dask/dask-image/issues/260
* PR fix: https://github.com/dask/dask-image/pull/261

**Comment by GenevieveBuckley** [comment]
Here we go: https://github.com/dask/dask-image/releases/tag/v2022.09.0

Try it out and tell me if there are any problems.

The release notes say "This will automatically upload the release to PyPI, and will also automatically begin the process to release the new version on conda-forge."
I'll have to check https://github.com/conda-forge/dask-image-feedstock for the bot's PR tomorrow.

**Comment by GenevieveBuckley** [comment]
The new release should be available on conda-forge now I've merged this PR: https://github.com/conda-forge/dask-image-feedstock/pull/11

**Comment by thewtex** [comment]
@GenevieveBuckley thank you, thank you!! Much greener now! 🙏 💚
