### ISSUE TITLE
2023.03.0 release?

### ISSUE THREAD

**Issue by jakirkham** [dask/dask-image#297]
Recently we were discussing making a new release ( https://github.com/dask/dask-image/issues/258#issuecomment-1467168183 ). Wondering if there is anything else we want to get in that release

cc @GenevieveBuckley

**Comment by GenevieveBuckley** [comment]
I think we should just do it. 

A new release also closes issue https://github.com/dask/dask-image/issues/271, as well as this one.

**Comment by m-albert** [comment]
@GenevieveBuckley Ah yes, sorry for my confusing comment, that's what I meant :)

**Comment by GenevieveBuckley** [comment]
I've made a release candidate here: https://github.com/dask/dask-image/releases/tag/v2023.03.0-rc1

I think it's worth checking our new deploy script uploads the wheel correctly to PyPI (https://github.com/dask/dask-image/issues/271), then if that's all good we'll [draft a new release](https://github.com/dask/dask-image/releases) with tag v2023.03.0 and copy the release notes text there too.

**Comment by GenevieveBuckley** [comment]
Yes, the wheel has been uploaded properly to PyPI: https://pypi.org/project/dask-image/2023.3.0rc1/#files

**Comment by GenevieveBuckley** [comment]
Release v2023.03.0 made: https://github.com/dask/dask-image/releases/tag/v2023.03.0

**Comment by jakirkham** [comment]
Thanks Genevieve! 🙏
