### ISSUE TITLE
Python 2 is really slow

### ISSUE THREAD

**Issue by jakirkham** [dask/dask-image#30]
_From @jakirkham on August 7, 2017 23:15_

Not entirely sure what the cause of this issue is, but using `dask-ndmeasure` on Python 2 is pretty slow compared to using it on Python 3. For instance, running the test suite ends up being ~50% or more slower on Python 2 compared to Python 3. Given that Python 2 is legacy at this point, maybe this isn't a priority, but the issue is worth being aware of.

_Copied from original issue: dask-image/dask-ndmeasure#73_

**Comment by jakirkham** [comment]
Appears that the optimization of `minimum_position` and `maximum_position` in PR ( https://github.com/dask-image/dask-ndmeasure/pull/76 ) has helped. Looks like a minor speed up of ~15%. So this issue still remains.

**Comment by GenevieveBuckley** [comment]
We have now dropped support for Python 2 (see https://github.com/dask/dask-image/pull/119), so I'm closing this issue.

**Comment by jakirkham** [comment]
Thanks @GenevieveBuckley!
