### ISSUE TITLE
GPU CI build failures with python 3.10

### ISSUE THREAD

**Issue by GenevieveBuckley** [dask/dask-image#302]
The GPU CI is having build failures (succeeds for python 3.8, fails for python 3.10)

Can our NVIDIA hero @jakirkham take a look?

Here are some recent examples:
- https://gpuci.gpuopenanalytics.com/job/dask/job/dask-image/job/prb/job/dask-image-prb/95/
- https://gpuci.gpuopenanalytics.com/job/dask/job/dask-image/job/prb/job/dask-image-prb/93/

I've poked around [in the console output](https://gpuci.gpuopenanalytics.com/job/dask/job/dask-image/job/prb/job/dask-image-prb/95/CUDA_VER=11.5,LINUX_VER=ubuntu18.04,PYTHON_VER=3.10/console), and found this:
```
13:39:52 continuous_integration/gpuci/build.sh: line 58:   107 Aborted                 (core dumped) py.test $WORKSPACE -v -m cupy --junitxml="$WORKSPACE/junit-dask-image.xml"

13:39:52 Build step 'Execute shell' marked build as failure
```

The [GPU CI build script is here](https://github.com/dask/dask-image/blob/main/continuous_integration/gpuci/build.sh), but that doesn't give me any more clues about why the core was dumped:

https://github.com/dask/dask-image/blob/325f880170364397b425e3efabab01421f2b7dba/continuous_integration/gpuci/build.sh#L58

**Comment by jakirkham** [comment]
Thanks Genevieve! 🙏

This is a good question. Are we seeing this fail reliably or is it intermittent?

**Comment by GenevieveBuckley** [comment]
> Thanks Genevieve! 🙏
> 
> This is a good question. Are we seeing this fail reliably or is it intermittent?

It's possible we might have to click the "dispatch workflow" button on the github actions tab a few times to know this for sure.

There was a PR in between the two I listed above PR 93 & 95 had this failure, but PR 94 did not. But in all three cases, I wasn't editing actual code, more documentation and settings sections, so it might just have skipped the cupy CI tests?

**Comment by jakirkham** [comment]
Gotcha. Well let's keep an eye on it. If we see it reoccur, can take a closer look

**Comment by GenevieveBuckley** [comment]
I don't know if this has still been happening intermittently or not. I think we'll close this issue, and can always re-open it if we see this behaviour again.
