### ISSUE TITLE
Move from `setup.py` to `pyproject.toml`

### ISSUE THREAD

**Issue by jakirkham** [dask/dask-image#305]
Increasingly there is a move by Python projects to use `pyproject.toml` to declare their metadata and dependencies and away from `setup.py`. Raising this issue to start discussion around how to approach this in Dask-image.

<hr>

Related upstream issues:
* https://github.com/dask/dask/issues/10032
* https://github.com/dask/distributed/issues/7622

**Comment by GenevieveBuckley** [comment]
The only points for discussion I can think of are:
- flake8 is not supported in pyproject.toml files directly, we'd need to add [Flake8-pyproject](https://pypi.org/project/Flake8-pyproject/) as a dependency
- ...there are additional flake8 problems unrelated to this, I'll open another issue to discuss

**Comment by GenevieveBuckley** [comment]
Hm, perhaps one other problem is that with the pyrpoject.toml setup, it looks as though dask-image version 0.0.0 is installed for the development version. That is what appears in the conda list, and I think that'll end up being a bit of a problem. (But if you import dask-image and check the __version__ string, you see the expected version)

**Comment by GenevieveBuckley** [comment]
Maybe [FlakeHell](https://flakehell.readthedocs.io/). This blogpost seems encouraging: https://dev.to/bowmanjd/using-flake8-and-pyproject-toml-with-flakehell-1cn1
