### ISSUE TITLE
Drop python 3.8

### ISSUE THREAD

**Issue by GenevieveBuckley** [dask/dask-image#314]
The Dask community is discussing dropping python 3.8 here https://github.com/dask/community/issues/315

I think we should follow that discussion and do the same thing here. It looks as though the consensus is leaning towards dropping python 3.8 soon-ish.

**Comment by jakirkham** [comment]
SGTM

AIUI that would also fix CI. Is that right?

**Comment by GenevieveBuckley** [comment]
I think so. 
I think it's only the python 3.8 Ci environment that has that particular problem with the pandas and dask versions being incompatible https://github.com/dask/dask-image/issues/312

**Comment by jakirkham** [comment]
Think it would be ok if we wanted to drop Python 3.8 before dask does (since dask-image is downstream of dask)
