### ISSUE TITLE
`dask_image.ndmeasure.label` gives different results compared to `scipy.ndimage.label`

### ISSUE THREAD

**Issue by vecxoz** [dask/dask-image#320]
Hi!
I have a binary 3D array and I need to perform connected-component labeling. In my experiments `dask_image` produces different results compared to `scipy`. Another observation is that the number of labels returned by `dask_image` depends on the input `dtype`. Do I actually do everything correctly? Thanks in advance!

```python
import numpy as np # 1.23.5
import scipy # 1.10.1
from dask_image import ndmeasure # 2023.03.0

np.random.seed(0)
X = np.random.choice([0, 1], size=(800, 800, 800), p=[0.7, 0.3]).astype(np.uint8)
structure = scipy.ndimage.generate_binary_structure(3, 3) 

# scipy
label_1, n_labels_1 = scipy.ndimage.label(X, structure)
print(n_labels_1) # 18533

# dask_image
label_2, n_labels_2 = ndmeasure.label(X, structure)
print(n_labels_2.compute()) # 18534

print((label_1 == label_2.compute()).all()) # False
```

**Environment**:

- Dask version: 2023.5.0
- Python version: Python 3.10.10
- Operating System: Ubuntu 20.04.6 LTS
- Install method: pip

**Comment by jakirkham** [comment]
Thanks for the report! 🙏

The labels will be different as designing the algorithm to work in a distributed way required some rethinking

That said, maybe it would be worth computing some kind of similarity matrix between the masks corresponding to each label? Could then threshold this to find the most likely corresponding labels. This might give us a better idea of which labels are related between the two results (as the order may be different) and how far off they are from each other. We could also dig a bit more into the kinds of differences seen between the algorithms

**Comment by vecxoz** [comment]
Hi @jakirkham,
Thank you for your reply. Of course a distributed approach always makes the implementation a bit sophisticated. Btw, I have a question regarding the input size. I found that when the input array is relatively small (e.g. 400x400x400 and smaller) results are identical with `scipy`. But when the input size increases the result starts to deviate. What do you think, is it a coincidence, or there may be some specific relation? Thanks!

**Comment by jakirkham** [comment]
cc @jni (who may also have thoughts here)

**Comment by jakirkham** [comment]
Thanks Marvin! 🙏 Was debating asking as it may make easier to see how things are changing 😄

**Comment by GenevieveBuckley** [comment]
Closed by https://github.com/dask/dask-image/pull/321
