### ISSUE TITLE
Failing GPU test that isn't run by the gpuCI 

### ISSUE THREAD

**Issue by m-albert** [dask/dask-image#327]
I just ran local tests with cupy installed and got a failing test:

```python
>       out = threshold_local(self.image, block_size, method='gaussian')

tests/test_dask_image/test_ndfilters/test_cupy_threshold.py:37:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
dask_image/ndfilters/_threshold.py:87: in threshold_local
    thresh_image = _gaussian.gaussian_filter(image, sigma, mode=mode,
dask_image/ndfilters/_gaussian.py:65: in gaussian_filter
    sigma = _get_sigmas(image, sigma)
dask_image/ndfilters/_gaussian.py:25: in _get_sigmas
    nsigmas = np.array(sigma)
../../miniconda3/envs/test_dask_image/lib/python3.10/site-packages/dask/array/core.py:1703: in __array__
    x = np.array(x)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   ???
E   TypeError: Implicit conversion to a NumPy array is not allowed. Please use `.get()` to construct a NumPy array explicitly.

cupy/_core/core.pyx:1480: TypeError
```
I think the error makes sense, as `sigma` is passed as a cupy backed dask array by `dask_image.ndfilters.threshold_local`:

https://github.com/dask/dask-image/blob/91ea2802a919d3d30198e9473713236ecbc8003e/dask_image/ndfilters/_threshold.py#L83

However, somehow the gpuCI doesn't pick it up.

`tests.test_dask_image.test_ndfilters` contains `test_cupy_ndfilters.py` and `test_cupy_threshold.py`. For some reason the tests in the former are run and the test defined in the latter is [ignored](https://gpuci.gpuopenanalytics.com/job/dask/job/dask-image/job/prb/job/dask-image-prb/lastSuccessfulBuild/CUDA_VER=11.5,LINUX_VER=ubuntu18.04,PYTHON_VER=3.10/testReport/tests.test_dask_image.test_ndfilters/)... Why could this be?

**Comment by GenevieveBuckley** [comment]
I don't have good insight into the gpuCI. Perhaps @jakirkham or @charlesbluca might have a better idea about what might be going wrong here?

**Comment by jakirkham** [comment]
We seem to be using an old `class`-style setup in the threshold modules (with a decorator), 

Maybe we should move away from this structure to something more similar to typical `pytest` usage (like functions maybe with a `fixture`)

https://github.com/dask/dask-image/blob/fba66458a49c815153fda7cb1b322e2a0c8c5d98/tests/test_dask_image/test_ndfilters/test_cupy_threshold.py#L20

https://github.com/dask/dask-image/blob/fba66458a49c815153fda7cb1b322e2a0c8c5d98/tests/test_dask_image/test_ndfilters/test__threshold.py#L16

**Comment by m-albert** [comment]
Think I found the problem. Trying to recreate the [way the gpuci performs tests](https://github.com/dask/dask-image/blob/fba66458a49c815153fda7cb1b322e2a0c8c5d98/continuous_integration/gpuci/build.sh#L43) I realized that the ignored function is not marked with `@pytest.mark.cupy`. Marking it includes it in the tests, at least locally.
