### ISSUE TITLE
Require CuPy 9.0.0+

### ISSUE THREAD

**Issue by jakirkham** [dask/dask-image#328]
At this point CuPy 9.0.0 has what we need as discussed in PR ( https://github.com/dask/dask-image/pull/325 )

Perhaps we should update requirements and [`importorskip` lines]( https://github.com/search?q=repo%3Adask%2Fdask-image+importorskip&type=code ) to match

**Comment by jakirkham** [comment]
On 2, we might want to make add `cupy` as an [optional dependency]( https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#optional-dependencies ) with a version constraint. This is partially motivated by simply documenting what we intend to support (though it may also act as an installation convenience)

**Comment by m-albert** [comment]
Great idea. To have it linked here, @GenevieveBuckley is incorporating cupy as an optional dependency into the pyproject.toml https://github.com/dask/dask-image/pull/306

**Comment by GenevieveBuckley** [comment]
Closed by https://github.com/dask/dask-image/pull/306/files
See:
https://github.com/dask/dask-image/blob/8393093c1d073dd0dfff9a33e57584b1e8bf8c73/pyproject.toml#L48
