### ISSUE TITLE
imread does not preserve dimensions order if one dimension is 3

### ISSUE THREAD

**Issue by aeisenbarth** [dask/dask-image#341]
I am trying to read a CYX ImageJ tifffile. It may have 1, 2 or 3 channels, but is not RGB. When there are 3 channels, channels become the last dimension (like RGB), which means my code might take it as X dimension.

It looks like there is a heuristic that takes action only when the third-last dimension is 3, and the spatial dimensions x,y > 4.

dask==2023.8.1
dask-image==2023.8.1
scikit-image==0.21.0

```python
import numpy as np
import dask.array.image
from pathlib import Path
import pytest
import tifffile


@pytest.mark.parametrize(
    "shape",
    [
        (1, 4, 4),
        (2, 4, 4),
        (3, 4, 4),
        (3, 5, 5), # Fails
        (4, 4, 4),
    ],
)
@pytest.mark.parametrize(
    "dtype",
    [
        np.uint8,
        np.uint16,
        np.int16,
        np.float32,
    ],
)
def test_imread_channels(shape, dtype, tmp_path):
    array = np.zeros(shape, dtype=dtype)
    output_path = Path(tmp_path, "img.tiff")
    tifffile.imwrite(
        output_path,
        array,
        imagej=True,
        metadata={"axes": "CYX"},
    )
    written_shape = tifffile.imread(output_path).shape
    # assert written_shape == shape
    # It prepends a singleton dimension
    expected_shape = (1,) + written_shape if written_shape[0] != 1 else written_shape
    read_shape = dask.array.image.imread(str(output_path)).shape
    assert read_shape == expected_shape, "Dask imread did not read shape in order as written"

```

**Comment by m-albert** [comment]
Hi @aeisenbarth, thanks for opening the issue and the detailed tests to reproduce.

I realised you're using `dask.array.image`, while this repository implements `dask_image.imread.imread`. These two imread implementations currently coexist, which is pretty confusing.

I'm not entirely sure about the logic above regarding the expected shapes, but your tests pass when comparing the input shape to the one read by `dask_image.imread.imread`.
<details>
  <summary>Code</summary>

```python
import numpy as np
import dask.array.image
from pathlib import Path
import pytest
import tifffile

# from dask.array.image import imread
from dask_image.imread import imread

@pytest.mark.parametrize(
    "shape",
    [
        (1, 4, 4),
        (2, 4, 4),
        (3, 4, 4),
        (3, 5, 5), # Fails
        (4, 4, 4),
    ],
)
@pytest.mark.parametrize(
    "dtype",
    [
        np.uint8,
        np.uint16,
        np.int16,
        np.float32,
    ],
)
def test_imread_channels(shape, dtype, tmp_path):
    array = np.zeros(shape, dtype=dtype)
    output_path = Path(tmp_path, "img.tiff")
    tifffile.imwrite(
        output_path,
        array,
        imagej=True,
        metadata={"axes": "CYX"},
    )
    # written_shape = tifffile.imread(output_path).shape
    # assert written_shape == shape
    # It prepends a singleton dimension
    # expected_shape = (1,) + written_shape if written_shape[0] == 1 else written_shape
    expected_shape = shape
    read_shape = imread(str(output_path)).shape

    assert read_shape == expected_shape, "Dask imread did not read shape in order as written"
```

**Comment by cgohlke** [comment]
[dask.array.image.imread](https://docs.dask.org/en/stable/generated/dask.array.image.imread.html) uses [skimage.io.imread](https://scikit-image.org/docs/stable/api/skimage.io.html#skimage.io.imread) by default, which returns RGB/A color samples in the last dimension. Try a different backend, e.g., `dask.array.image.imread(..., imread=tifffile.imread)`.

**Comment by aeisenbarth** [comment]
Thanks, that is the work-around I found (still, I don't understand why skimage is unpredictable, if it's focus is YXC RGB, it should rather refuse reading higher-dimensional files than doing it inconsistently).

It was a wrong import in code I didn't write. With the correct import from dask-image it works nicely, preserving dimensions order and not prepending singleton dimensions.

**Comment by cgohlke** [comment]
> I don't understand why skimage is unpredictable, if it's focus is YXC RGB, it should rather refuse reading higher-dimensional files than doing it inconsistently).

There were several issues reported and long discussions held over the years. At some point [skimage.io will probably be deprecated](https://github.com/scikit-image/scikit-image/issues/5036) or replaced by imageio.
