### ISSUE TITLE
`readthedocs` build started failing in PRs and complains about wrong `sphinx` version

### ISSUE THREAD

**Issue by m-albert** [dask/dask-image#351]
readthedocs started to [throw errors `Sphinx version error`](https://readthedocs.org/projects/dask-image/builds/23503914/) in PRs such as https://github.com/dask/dask-image/pull/213 or https://github.com/dask/dask-image/pull/344. However, there were no changes to the readthedocs configuration and dependencies are all pinned.

It seems that sphinx 4.5. is being used for the build although version 5.3. is pinned here

https://github.com/dask/dask-image/blob/d241e7a354db6525691a72bfc8b78b2dc3e322c0/continuous_integration/environment-doc.yml#L10

What's interesting is that `cat continuous_integration/environment-doc.yml` on the [readthedocs](https://readthedocs.org/projects/dask-image/builds/23503914/) shows something different than `continuous_integration/environment-doc.yml` in the repository. Namely, there's a conda dependency sphinx added at the end, as if readthedocs added lines in the background.

I posted a [question](https://stackoverflow.com/questions/78029128/readthedocs-build-fails-with-sphinx-version-error) on stackoverflow regarding this.

**Comment by m-albert** [comment]
Thanks John 🙏

I created an issue upstream as you suggested.

**Comment by jakirkham** [comment]
Thank Marvin! 🙏

Yeah let's see what they say

Sounds plausible

**Comment by GenevieveBuckley** [comment]
Closing this issue now #354 is merged.

There is still some follow up work planned (removing the sphinx dependencies [pinned in #354](https://github.com/dask/dask-image/pull/354/files) when sphinx v5 is consistently being installed in the test environment. If needed, we can open a new issue to track this follow up.
