### ISSUE TITLE
ndinterp methods fails with ResourceBackedDaskArray from aicsimageio

### ISSUE THREAD

**Issue by sommerc** [dask/dask-image#360]
Hi there,

I want to use `ndinterp.affine_transform` on images loaded with aicsimageio/[nd2](https://github.com/tlambert03/nd2/issues). For some image formats (e.g. `.nd2`) aicsimageio returns a [ResourceBackedDaskAray](https://github.com/tlambert03/resource-backed-dask-array) which is an instance of `da.Array`. 

However the [type check](https://github.com/dask/dask-image/blob/b23b6156f0df36a26a007a3701e5680fbddeacab/dask_image/ndinterp/__init__.py#L86C1-L87C37) for `da.core.Array` fails.

```python
img = AICSImage("image.nd2")
affine_transform(img.dask_data, matrix)

ValueError: Array is already a dask array. Use 'asarray' or 'rechunk' instead.
```

Cheers,
Chris

**Comment by m-albert** [comment]
Hi @sommerc, thanks for posting this issue 🙏

This is the line behind the type check you mentioned: 

```python
type(image) == da.core.Array
```

We should probably look into whether this is the right way to perform this check. Would you be aware of a check that `ResourceBackedDaskArray`s passes?

**Comment by sommerc** [comment]
Hi @m-albert,

thanks for your quick reply! I am not an expert on dask, but

`isinstance(image, da.core.Array)` is True for image of type `ResourceBackedDaskArray`

and should not do any harm. 

C

**Comment by m-albert** [comment]
Thanks! Probably we should be using `isinstance` in `dask_image.ndinterp` to also support dask array sublcasses, as your example clearly motivates.

Would you be interested in creating a PR for this @sommerc ?

**Comment by sommerc** [comment]
Yes, then it would also match the check inside `da.from_array()` 

> Would you be interested in creating a PR

Absolutely, I'll create on tomorrow.

Thanks a lot!
