### ISSUE TITLE
Stable docs page shows development version

### ISSUE THREAD

**Issue by dstansby** [dask/dask-image#375]
At https://image.dask.org/en/stable/, there's a non-stable version shown:

<img width="278" alt="Screenshot 2024-05-17 at 11 22 43" src="https://github.com/dask/dask-image/assets/6197628/4993916c-bcc9-4f5d-9013-9e1ff40aa90e">

I'm guessing this should be a stable version?

**Comment by GenevieveBuckley** [comment]
This might be because [ReadTheDocs expects ](https://docs.readthedocs.io/en/stable/versions.html#how-we-envision-versions-working) ([like these examples](https://packaging.python.org/en/latest/specifications/version-specifiers/#examples-of-compliant-version-schemes)), and the [dask-image version tags](https://github.com/dask/dask-image/tags) all start with the letter `v`.

**Comment by GenevieveBuckley** [comment]
> This might be because [ReadTheDocs expects ](https://docs.readthedocs.io/en/stable/versions.html#how-we-envision-versions-working) ([like these examples](https://packaging.python.org/en/latest/specifications/version-specifiers/#examples-of-compliant-version-schemes)), and the [dask-image version tags](https://github.com/dask/dask-image/tags) all start with the letter `v`.

This can probably be solved by using [a custom match](https://docs.readthedocs.io/en/stable/automation-rules.html#custom-matches) in the [automation rules](https://blog.readthedocs.com/automation-rules/) for ReadTheDocs.

@jakirkham will probably have to do this: it looks like you have to log in to ReadTheDocs to both (1) set automation rules, and (2) activate any tags ReadTheDocs has not previously identified as a version tag. 

I tried logging in to ReadtheDocs with github, but I don't see anything related to dask-image linked to my account.

**Comment by GenevieveBuckley** [comment]
Separate to this discussion, the main docs page at https://image.dask.org does redirect to https://image.dask.org/en/latest/ (not stable). That is deliberate, from my understanding (mostly because we often have a delay between a new feature going in and an official release being made. It seems better if people know a new thing exists rather than not know)

**Comment by jakirkham** [comment]
> I tried logging in to ReadtheDocs with github, but I don't see anything related to dask-image linked to my account.

@GenevieveBuckley What is your handle on RTD?

@m-albert would you like access to RTD as well? If so, what is your handle?

**Comment by GenevieveBuckley** [comment]
> @GenevieveBuckley What is your handle on RTD?

It's GenevieveBuckley
That's what I see in the top right hand corner with the account name, and it makes sense to me that if I've logged in via Github then they'd both be the same.

**Comment by jakirkham** [comment]
Added. They say there is some kind of invitation that you need to accept. Guessing in email

**Comment by jakirkham** [comment]
Also started [a new build]( https://readthedocs.org/projects/dask-image/builds/24438066/ ) for the latest tag. Guessing this will fix this issue

**Comment by jakirkham** [comment]
Ok that wasn't enough. Think we also need to change this logic to reflect `setuptools-scm`

https://github.com/dask/dask-image/blob/d3c944ffeb976ff420f43830ec947980ce67c0c7/docs/conf.py#L19

https://github.com/dask/dask-image/blob/d3c944ffeb976ff420f43830ec947980ce67c0c7/docs/conf.py#L66-L73

**Comment by jakirkham** [comment]
Interesting it looks like both of these tags are on the same commit. Is that expected?

<img width="1840" alt="Screenshot 2024-05-20 at 7 56 57 PM" src="https://github.com/dask/dask-image/assets/3019665/6ebed6a6-4526-47c3-801c-522e14d89f6e">

**Comment by jakirkham** [comment]
Looks like there was [a new build]( https://readthedocs.org/projects/dask-image/builds/24438562/ ) with [the `2024.5.1` tag]( https://github.com/dask/dask-image/releases/tag/v2024.5.1 ) added recently

**Comment by jakirkham** [comment]
Interesting this shows the right tag at the bottom in RTD. However the rendered docs look off

Maybe there is a `setuptools-scm` setting we are missing?

<img width="1840" alt="Screenshot 2024-05-20 at 9 34 45 PM" src="https://github.com/dask/dask-image/assets/3019665/ea61e2ac-ee64-4a48-910a-c1bf64668916">

**Comment by m-albert** [comment]
> @m-albert would you like access to RTD as well? If so, what is your handle?

Thanks @jakirkham! My handle on readthedocs is "m-albert" (also over github)

**Comment by GenevieveBuckley** [comment]
> Interesting it looks like both of these tags are on the same commit. Is that expected?

That is what I did. 
Although I wasn't really thinking about which commit tags were being attached to, I just tried to make a release candidate version, then realised conda-forge would only build for real releases, and made another tag for that. I mostly just wanted to trigger the release deployment. If it's causing a problem, maybe we can get rid of the the `rc1` tag somehow (no one will care about that)

**Comment by GenevieveBuckley** [comment]
I found the problem!
The default `html_title` parameter in the `docs/conf.py` is using the full release name, not the shorter release version. That's what's getting passed into the dask sphinx template and being displayed in the top left corner.

https://github.com/dask/dask-image/blob/main/docs/conf.py#L131-L133

Hang on a sec, I'll make a fix...

**Comment by jakirkham** [comment]
> > @m-albert would you like access to RTD as well? If so, what is your handle?
> 
> Thanks @jakirkham! My handle on readthedocs is "m-albert" (also over github)

Added. Please look for an invite (likely in email)

**Comment by jakirkham** [comment]
To the issue at hand, was looking at RTD's own documentation and spotted [this recommendation]( https://docs.readthedocs.io/en/stable/build-customization.html#avoid-having-a-dirty-git-index )

Namely RTD changes some files in the repo as part of their build process. The result is the repo appears dirty to git (as there are unstated changes to tracked files). They recommended telling `git` in the RTD build process to ignore these changed files

Included these changes in PR ( https://github.com/dask/dask-image/pull/378 ) along with a test in RTD to ensure the repo is clean. Also tagged as [2024.5.3]( https://github.com/dask/dask-image/releases/tag/v2024.5.3 ). Looking at the RTD build, this appears to do the right thing

<img width="1840" alt="Screenshot 2024-05-21 at 5 15 59 PM" src="https://github.com/dask/dask-image/assets/3019665/b5265a3e-5ddd-4e40-b9ca-34e6e6bf2950">
